### ISSUE TITLE
Shift works unexpectedly for negative values

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#105]
Given
```Rust
let s = Series::new("series", &[1, 2, 3]);
```

If you call `s.shift(1)`, you get `&[None, Some(1), Some(2)]`. This does what it says on the tin: everything was shifted right 1 slot and a `None` filled the empty space.

But if you call `s.shift(-1)`, you get something very different: `&[Some(1), Some(2), None]`. This is really a `fill_from_end(n, None)`. It filled the last `n` values with `None`. If it were shifting values left 1 slot I'd expect to get `&[Some(2), Some(3), None]`

**Comment by ritchie46** [comment]
I see that I even tested it with the wrong values :sweat_smile:.

**Comment by TheDan64** [comment]
Thanks for the quick fix!

Fyi, this is still incorrect in the python tests: https://github.com/ritchie46/polars/blob/master/py-polars/tests/test_series.py#L187-L188
