### ISSUE TITLE
Lot of time taken to convert to dataframe

### ISSUE THREAD

**Issue by chinmayyadav** [ritchie46/polars#110]
I am using the following code to convert a csv file of size 950 MB to a dataframe, and it takes more than 2.5 minutes to just convert it to dataframe. 
`let file = File::open("sample.csv")
                .expect("could not read file");

let df = CsvReader::new(file)
.infer_schema(Some(100))
.has_header(true)
.with_batch_size(10000000)
.finish()
.unwrap()`

Is there something I am doing wrong or is there some faster way to do this? Because after the dataframe is made, all the operations are done very quickly. I could not find anything regarding this. Can anyone please help?

**Comment by ritchie46** [comment]
Are you running in `--release` mode?

**Comment by chinmayyadav** [comment]
No I was not running in --release mode, I tried using --release and it now converted to a dataframe in around 20 seconds.

Thank You for Replying

**Comment by ritchie46** [comment]
No problem. If you need to read in the same file often CSV are not optimal. After you've read to a DataFrame you could write the DF to an IPC file. This is a binary format, which should be a lot faster to read.

**Comment by chinmayyadav** [comment]
Okay, Thank You
