### ISSUE TITLE
Attempt to subtract with overflow when calling dbg!(series)

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#111]
```Rust
let mut s = Series::new("s", Vec::<f64>::new());

s.append(&Series::new("s2", vec![1., 2., 3.]))?;

dbg!(&s);
```

`panicked at 'attempt to subtract with overflow', polars-0.7.3\src\chunked_array\mod.rs:390:16`

**Comment by ritchie46** [comment]
That is because the first chunk has a length of zero. I knew this problem was coming but ignored it until now. Will fix it.
