### ISSUE TITLE
Add temporal utilities

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#126]
Often we need to deal with temporal data. I want to be able to get the hour, year, weekday, etc. out of the temporal datatypes. There is already Chrono conversion, so should use that

**Comment by nevi-me** [comment]
Hey Ritchie, there's https://issues.apache.org/jira/browse/ARROW-5367 and https://github.com/apache/arrow/blob/master/rust/arrow/src/compute/kernels/temporal.rs, where more of the functions can live

**Comment by ritchie46** [comment]
Yes.. I've seen them. I am currently already using py-polars in daily work, so that I can faster implement something when I need it. 
I was thinking to structure the temporal logic around kernels such that I could easily switch between kernels implemented upstream by Arrow or in this crate.

**Comment by ritchie46** [comment]
17d187d648408be713d369eb053c87a26cf1ea2d
