### ISSUE TITLE
It's possible to add two separate columns with the same name

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#127]
```Rust
df.add_column(Series::new("col", data1))?;
df.add_column(Series::new("col", data2))?;
```

I expected that the second one would overrwrite the first; but instead `df.head(None)` reveals both those columns exist at the same time, despite sharing the same name. Doing `df["col"]` appears to select the first one.

**Comment by ritchie46** [comment]
Yes.. I knew that. And I ignored that. But I shouldn't. Will fix it!

**Comment by marioloko** [comment]
In my opinion the current behavior, having two columns with the same name, is wrong. However, I wouldn't replace the current column if the column exists. What I think is the best to do in this cases is either:
1. Add a new column with a different name `col` would be inserted as `col_2`.
2. If the column already exist, then, return an `Error` and it is up to the user how to handle this. Of course, there should be also a method `replace_column` or a similar mechanism to allow the user to replace the column in case the column already exist.

**Comment by ritchie46** [comment]
Yes.. Maybe we could something similar to [entry](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry) in the hashmaps.

**Comment by marioloko** [comment]
Yes, that sounds cool. With methods like `.or_insert` or `.and_replace`.

**Comment by TheDan64** [comment]
Well, if you're going to mimic the entry api, `insert` would be always overwriting
