### ISSUE TITLE
Python: list comprehension over a DataFrame

### ISSUE THREAD

**Issue by estebanz01** [ritchie46/polars#140]
hey! Amazing tool you got here. I was doing some experiments to see up to which point is feasible to replace pandas with pypolars, so I ran a couple of small tests, and I got some weird behaviours.

##### Process hang while calculating tuples.
```python
>>> df = pl.DataFrame({ "hola": np.random.rand(10), "adios": np.arange(10) })
>>> df.head()
+-------+-------+
| hola  | adios |
| ---   | ---   |
| f64   | i64   |
+=======+=======+
| 0.7   | 0     |
+-------+-------+
| 0.883 | 1     |
+-------+-------+
| 0.195 | 2     |
+-------+-------+
| 0.949 | 3     |
+-------+-------+
| 0.027 | 4     |
+-------+-------+

>>> df.head(10)
+-------+-------+
| hola  | adios |
| ---   | ---   |
| f64   | i64   |
+=======+=======+
| 0.7   | 0     |
+-------+-------+
| 0.883 | 1     |
+-------+-------+
| 0.195 | 2     |
+-------+-------+
| 0.949 | 3     |
+-------+-------+
| 0.027 | 4     |
+-------+-------+
| 0.417 | 5     |
+-------+-------+
| 0.605 | 6     |
+-------+-------+
| 0.981 | 7     |
+-------+-------+
| 0.851 | 8     |
+-------+-------+
| 0.961 | 9     |
+-------+-------+

>>> [x for x in df]
```

If I interrumpt the process, this is the stacktrace I get:
```python
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "venv/lib/python3.8/site-packages/pypolars/frame.py", line 290, in __getitem__
    return wrap_s(self._df.select_at_idx(item))
  File "venv/lib/python3.8/site-packages/pypolars/series.py", line 60, in wrap_s
    return Series._from_pyseries(s)
  File "venv/lib/python3.8/site-packages/pypolars/series.py", line 154, in _from_pyseries
    self._s = s
KeyboardInterrupt
```

##### I cannot access a column while applying list comprehensions
```python
>>> [row['hola'] for row in df]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "venv/lib/python3.8/site-packages/pypolars/series.py", line 340, in __getitem__
    return f(item)
TypeError: 'str' object cannot be interpreted as an integer
>>> [row[:,'adios'] for row in df_kml]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "env/lib/python3.8/site-packages/pypolars/series.py", line 340, in __getitem__
    return f(item)
TypeError: 'tuple' object cannot be interpreted as an integer
```

For this one, I can simply do `df['hola'].to_list()` and that will solve the issue, but this is a toy example of something bigger that I would like to rewrite, since there's no notion of `apply` at `DataFrame` level.

In the end, what I want to do is something like this `df.apply(lambda row: convert_coordinates(row['longitude'], row['latitude']), axis = 1)`.

I'll keep playing around with this package in the mean time, it solves a good chunk of performance issues so far 😬 .

**Comment by ritchie46** [comment]
Thanks! Good to hear that it can already help performance issues. :)

Polars is in rapid development. So keep track of the latest upgrades as they probably will increase ergonomics by a lot. 

I shall supports list comprehensions. Only it will not be in the way you suspect. Polars memory layout is column-oriented. Accessing rows is very expensive compared to column access. Therefore I want to make column-oriented looping the default.

At the moment you cannot apply a lambda over rows indeed. That would require some more work on the python/ rust interaction. However I have made arithmetic on DataFrames possible. You can multiply a DataFrame with a Series (and that will broadcast). Or you can multiply a DataFrame with an integer float (and that will also broadcast). 

Could this in combination with some filters solve your problem?

**Comment by estebanz01** [comment]
I will give it a shot. Thanks!

**Comment by ritchie46** [comment]
P.S. The release with DataFrame arithmetic and iterable DataFrames is now on pypi. If you need any help with your specific problem, maybe I can help. Let's have that discussion on [gitter](https://gitter.im/polars-rs/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
