### ISSUE TITLE
Optimization framework

### ISSUE THREAD

**Issue by Dandandan** [ritchie46/polars#145]
This issue tracks the state of an optimization framework for polars.

The idea here is to make adding optimizations easy by having a bit of abstraction around the expression tree.

An example of it is readable in this paper: http://people.csail.mit.edu/matei/papers/2015/sigmod_spark_sql.pdf 

Some properties of this optimization framework:

* Addition of rules is easy, recursion is left out of the rules, and uses simple pattern matching
* Optimizing parts of the tree until reaching  a fixed point (keep applying rules in a loop until it doesn't change)

**Comment by Dandandan** [comment]
I think the best way to introduce it is by taking one of the passes (e.g. simplify expressions), separating recursion and pattern matching, implementing the fixed point iteration loop and seeing whether it can be reused for other passes / rules as well.

**Comment by Dandandan** [comment]
A bit of inspiration can be found in Sparks source code https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala

**Comment by Dandandan** [comment]
Here the code that executes the rules:
https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/rules/RuleExecutor.scala#L205

Notes: rules/batches are applied serially until reaching fixed point individually. So in the framework, the order of how to apply the rules is still important.

**Comment by ritchie46** [comment]
Right.. I've skimmed a bit through the paper. Would indeed be very cool if we can easily add rules to modify the LP. Can multiple rules be applied during a single pass trough a tree.

**Comment by Dandandan** [comment]
I think it is worthwhile to investigate. I think the catalyst optimizer only applies a single rule for the entire tree at the time (can be multiple replacements in a single "batch" though).
If you do multiple at once, on the plus side, you need fewer passes through the tree, on the other hand you also keep matching rules that only are applied only once. Have a feeling that it could still be a better choice though, also provides more opportunities to optimize as the order of the rules becomes less relevant this way.

**Comment by Dandandan** [comment]
Added first iteration here: https://github.com/ritchie46/polars/pull/149

**Comment by Dandandan** [comment]
I think we also need to change the representation of the `LogicalPlan` and `Expr` for this to work nicely.

I think it is best to have, at the start of the optimization convert it to the more optimal representation and at the and convert it back to a `LogicalPlan` when done.

Some options:
* (Fastest, most flexible) Arena-based logical plan / expression tree. Simple example of this is https://dev.to/deciduously/no-more-tears-no-more-knots-arena-allocated-trees-in-rust-44k6. Benefits of this are that allocation is seldom necessary and clones are not needed, as you can just mutate a particular value in the arena. Downside is that you need to use keep indexes to the array/vec in the tree (e.g. `NodeId`s) and you do not  ever drop anything from the allocated memory until you free the arena.
I currently think this is the best option.

* Use `Rc<RefCell<T>>`  (or `Arc<Refcell<T>>`) throughout. Makes it slower and has high syntactic overhead.

* Use `Rc` / `Arc` and don't mutate the data but generate new subtrees (immutable data structure, like this: https://docs.rs/immutable/0.1.1/src/immutable/tree/binary_tree.rs.html)  I think this will be the easiest besides doing nothing.

* Keep `clone()`ing the sub trees in the rules. However, this will probably make it slow once you have a large nr. of rules / deep plans / optimizations that fire regularly.

* Do some unsafe things with pointers (?)

Some extra material I found here:

https://github.com/SimonSapin/rust-forest

**Comment by Dandandan** [comment]
WIP PR here:
https://github.com/ritchie46/polars/pull/162

**Comment by ritchie46** [comment]
I consider this implemented. Maybe could use the LogicalPlan and Expression arena as default representation of the LP.

**Comment by Dandandan** [comment]
Yes, and try to get more of the passes in the framework. But that could follow later of course :)

**Comment by ritchie46** [comment]
>Yes, and try to get more of the passes in the framework.

Yes. Especially type-coercion should be in there. The pushdown's are bit more complicated.
