### ISSUE TITLE
Reduce size of logicalplan.

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#169]
A lot of operations can be represented with `apply` and `DataFrameOp` in the `Expr` and `Logicalplan`. This will simplify the optimizers and maintainability.

**Comment by Dandandan** [comment]
Which cases can be replaced by Apply? As it contains a `function: Arc<dyn Udf>` it would restrict possibility of optimizing over it.

I think indeed there is some duplication between DataframeOp and the logical plan. 

To me it might sound like a good idea to remove the DataFrameOp struct / alternative?
For me the LogicalPlan structure feels a bit more flexible than the DataFrameOp. 

Those items could be converted to Exp I guess:

    Reverse,
    Shift {
        periods: i32,
    },
    Explode(String)

Those to use aggregations AggMean(expr), AggMax(expr), etc?


    Max,
    Min,
    Sum,
    Mean,
    Median,
    Quantile(f64),


Sort / Reverse could be added to logical plan as OrderBy (with Asc/Desc) which they both can use?

And finally, DropDuplicates and DropNulls could be translated into aggregate + filter and filter ?

That would make it easier for optimizer and implementation as well.

**Comment by ritchie46** [comment]
Yes.. You are right, there is some redundancy. I agree that it's more clear to define them as part of the logical_plan. I do think that we should keep the  `DataFrameOp`  in the physical executor though. This saves a lot of code duplication and makes it easier to add a variant.

> Those items could be converted to Exp I guess:
How do you mean? The `Exp` work on `Series` whereas these operations 

```
Reverse,
Shift {
    periods: i32,
},
Explode(String)
```
Work on a whole DataFrame.

> Sort / Reverse could be added to logical plan as OrderBy (with Asc/Desc) which they both can use?

Sort can indeed. Reverse just reverses the DataFrame without sorting.

> And finally, DropDuplicates and DropNulls could be translated into aggregate + filter and filter ?

It could be defined like that in the logicalplan, but that implementation would be slower than the implementation currently used in `eager` for `drop_duplicates` and `drop_nulls`. Therefore they are separate operations.

**Comment by Dandandan** [comment]
Thanks for the answers. I don't know the internals of the library too much so I might say weird things :). 

> How do you mean? The Exp work on Series whereas these operations...

I would imaging 


Might it be better to keep the logicalplan and dataframe ops separated somehow? 

And for the drop_duplicates / drop_nulls would maybe be better if it's detected by the implementation?

For example if I would write df.filter(x == null), as a user I would expect it

**Comment by Dandandan** [comment]
The nice thing would be that they could also participate in the optimizations (e.g. projection pushdown) instead of just being executed as is.

**Comment by ritchie46** [comment]
Every operation in the LogicalPlan currently works on a DataFrame level. So it has a DataFrame (or LazyFrame) as input and returns a DataFrame. The expressions work on Series. They have a Series as input and return a Series.

So in this operation `df.filter(x == null)`, you filter the `DataFrame` by a `Series` coming from this `x == null` expression. (I assume that you meant `x` of type `Series`).

There is also a `drop_nulls`/ `drop_duplicates` implementation on the `DataFrame` level. This operations will not look at a column, but for

`drop_nulls` -> removes every row that has a single null value
`drop_duplicates` -> removes every duplicate row

These two operations have an implementation in the eager API that is faster than an implementation with aggregates/fitler would be.

**Comment by ritchie46** [comment]
@Dandandan You are correct about the fact that these can be represented as `Expr`

>I would imagine a df.max() with columns a,b,c, to be translated to this (use sql syntax for brevity):
select max(a) as a, max(b) as b, max(c) as c from df

`Reverse`, `Shift` for a whole DataFrame can probably be defined by:

```
df.select(reverse("*"))
df.select(shift("*", periods))
```
And could also be represented in the LogicalPlan as that.

**Comment by Dandandan** [comment]
I will need some time to understand I think :) 

Looking at this implementation:

```
    pub fn drop_nulls(&self, subset: Option<&[String]>) -> Result<Self> {
        let selected_series;

        let mut iter = match subset {
            Some(cols) => {
                selected_series = self.select_series(&cols)?;
                selected_series.iter()
            }
            None => self.columns.iter(),
        };

        let mask = iter
            .next()
            .ok_or_else(|| PolarsError::NoData("No data to drop nulls from".into()))?;
        let mut mask = mask.is_not_null();

        for s in iter {
            mask = mask & s.is_not_null();
        }
        self.filter(&mask)
    }

```

it looks like for every column/series in `subset` `.is_not_null` + final filter is being used? 

so wouldn't be

`df.drop_nulls(&["x"])`

be similar to

`df.filter(df.colum("x").is_not_null()`

Or would it be very different in some cases?

**Comment by ritchie46** [comment]
> so wouldn't be
df.drop_nulls(&["x"])
be similar to
df.filter(df.colum("x").is_not_null()

Yes, you are right, we could express this as a combination of predicates and a filter in the LogicalPlan. 

Last one! :smile: 
The drop_duplicates:

```rust
    pub fn drop_duplicates(&self, maintain_order: bool, subset: Option<&[String]>) -> Result<Self> {
        let names = match &subset {
            Some(s) => s.iter().map(|s| &**s).collect(),
            None => self.get_column_names(),
        };
        let gb = self.groupby(names)?;
        let groups = gb.get_groups().iter().map(|v| v.0);

        let df = if maintain_order {
            let mut groups = groups.collect::<Vec<_>>();
            groups.sort_unstable();
            let cap = Some(groups.len());
            unsafe { self.take_iter_unchecked(groups.into_iter(), cap) }
        } else {
            let cap = Some(groups.size_hint().0);
            unsafe { self.take_iter_unchecked(groups, cap) }
        };

        Ok(df)
    }
```

I think this would be best to keep as a separate operation in the LogicalPlan.  Or would you translate the eager implementation to a lazy one?

**Comment by Dandandan** [comment]
I think it would be better as a lazy one as well to have less alternatives in the plan and to make it easier for optimization as well... 

For example in some cases like `count * from x where a is not null and b is not null` we don't need the values of the filtering, only the mask (much much faster as it can use pop count and not keep the values or even push the filter down to a parquet / s3 / etc. reader). Having it as one case could make this (future) optimization a bit easier.

**Comment by Dandandan** [comment]
Ah I missed drop_duplicates. yes, might be better to keep it for the time being.

**Comment by Dandandan** [comment]
If we keep the nature of logical plan however, might be useful to call this Distinct rather than DropDuplicates? As Selection / Projection etc are also more "sql names" than drop duplicates. But also ok with keeping it like that.

**Comment by ritchie46** [comment]
> If we keep the nature of logical plan however, might be useful to call this Distinct rather than DropDuplicates? As Selection / Projection etc are also more "sql names" than drop duplicates. But also ok with keeping it like that.

Sure..

I shall make some issues such that `drop_nulls`, `shift` etc. can be replaced by lazy operations and close this issue in favor of them.
