### ISSUE TITLE
Unwrap `DataFrameOps` as separate nodes in the logicalplan.

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#171]
Following discussion in: #169 

This would expose all operations to the optimizer and give more control.

**Comment by ritchie46** [comment]
A lot done in #174

**Comment by Dandandan** [comment]
Cool, for me commits it shows it simplified the design a lot already 💯

**Comment by ritchie46** [comment]
Yes, and exposing more to the optimizer really feels like the better solution. :)
