### ISSUE TITLE
specified package `polars v0.8.1` has no binaries

### ISSUE THREAD

**Issue by sa-** [ritchie46/polars#177]
I'm unable to run `cargo install polars`because of this :(

**Comment by sa-** [comment]
Hey - I'm not sure if I'm doing something wrong because I'm fairly new to rust. I'd like to try out polars using the evcxr kernel in jupyter. When I try to run cargo install, I get 
`specified package `polars v0.8.1` has no binaries` and I'm not sure how to proceed. What's the best way forward?

**Comment by ritchie46** [comment]
That's correct. Polars is a library which you can depend on in a binary crate or another library crate. `$ cargo install` install binaries. 

I believe it should work if you add this in the evcxr repl.

`:dep porals = { git = "https://github.com/ritchie46/polars/" }`

**Comment by sa-** [comment]
Okay cool thank you!
It might be helpful to add this to the top cell in https://github.com/ritchie46/polars/blob/master/examples/10_minutes_to_polars.ipynb
