### ISSUE TITLE
CsvReader has heavy memory leak

### ISSUE THREAD

**Issue by zirconium-n** [ritchie46/polars#178]
```
/// Clone if upstream hasn't implemented clone
pub(crate) fn clone<T>(t: &T) -> T {
    unsafe { mem::transmute_copy(t) }
}
```
You declared this `clone` function and "cloned" the reader passed in. Honestly I'm surprised it's just memory leak not UB and segfault. This so called `clone` function is a total disaster, and I'm afraid your crate may not be sound at all.

**Comment by ritchie46** [comment]
This isn't used anymore in master. Did you refer to the 8.1 release? You are right that this function should be marked as unsafe or better yet deleted, to prevent the idea of memory safe cloning.

**Comment by zirconium-n** [comment]
Yes. I was not referring to master, since I just inspected local source file with cargo. This is a really bad bug, could you push a new release?

No offensive means, but after reading code relative to this issue, I'm moving away from polars :(

**Comment by ritchie46** [comment]
Polars 0.9.0 is out now. Give it a spin! :wink:
