### ISSUE TITLE
Optimize CSV Reader

### ISSUE THREAD

**Issue by Dandandan** [ritchie46/polars#187]
FYI, I opened a PR against Arrow optimizing the CSV reader. See comments / changes there.

https://github.com/apache/arrow/pull/8781

I guess those optimizations could be used here as well.
I think going further would be to stop using the iterator / StringRecord api altogether and use the lower level 
https://docs.rs/csv-core/0.1.10/csv_core/ library (created / used by the same library).

**Comment by ritchie46** [comment]
Great tip thanks! I was already trying to amortize allocations, but now you mention it and after inspecting the `next` method of the BytesIterator I see it clones at every record.

```rust
    fn next(&mut self) -> Option<Result<ByteRecord>> {
        match self.rdr.read_byte_record(&mut self.rec) {
            Err(err) => Some(Err(err)),
            Ok(true) => Some(Ok(self.rec.clone())),
            Ok(false) => None,
        }
```

So things I already tried/did:
 * use lexical (I saw your PR in Arrow :wink: )
 * Delay utf8 validation by using BytesRecords
 * amortize allocations (but this can be done better)

**Comment by Dandandan** [comment]
Yes. I also just pushed another optimization removing the BufReader, which just causes a slowdown rather than speedup besides making code more complicated.

**Comment by Dandandan** [comment]
But I see you already have removed that one :+1:  (there is one comment still)

**Comment by ritchie46** [comment]
Yes.. I believe the BufReader is in the csv-reader itself. So that would lead to two BufReaders.

**Comment by Dandandan** [comment]
Ah, you're right :)

**Comment by ritchie46** [comment]
Reused allocations in #188 

Benchmark reading csv on [Reddit usernames dataset](https://www.kaggle.com/colinmorris/reddit-usernames).

(3 runs) Time in seconds before:
```
7.45514884000022
7.461633311000696
7.641038990000197
```

After:

```
4.869877860000088
4.845668472999932
4.866918011999587
```

The parsing of the csv on multiple threads still needs some good critical examination.

**Comment by Dandandan** [comment]
Awesome, nice result!

**Comment by ritchie46** [comment]
@Dandandan Just thinking aloud here. Maybe you have got an idea about this? 

There is also an implementation where I send the `ByteRecords` over a channel to another thread that does the processing into arrow arrays. This seems to have better performance with CSV with a large number of columns (>100 columns). I could save allocations by sending full and empty vecs over a channel, but I wonder if this even makes sense.

How are channels implemented. Are they an abstraction over a mutex or some sort?
Is the overhead of channels cheaper than sys allocs?

Of course I should benchmark to find out, but maybe I can save some hours of prototyping.

**Comment by Dandandan** [comment]
I didn't do much with channels yet, but I think Vecs are both Send/Sync, and they shouldn't clone/copy.

**Comment by ritchie46** [comment]
Yes.. That's true.. I guess I just benchmark. :)
