### ISSUE TITLE
Panic with 'Arrow datatype Date32(Day) is not supported' when reading Parquet

### ISSUE THREAD

**Issue by davechallis** [ritchie46/polars#200]
Reading a Parquet file that contains this datatype causes a panic in 0.9.0:

```
use polars::prelude::*;
use std::fs::File;

fn main() -> Result<()> {
    let r = File::open("test.parquet")?;
    let reader = ParquetReader::new(r);
    let df = reader.finish()?;

    Ok(())
}
```

```
thread 'main' panicked at 'Arrow datatype Date32(Day) is not supported', /Users/dsc/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-0.9.0/src/frame/ser/mod.rs:135:18
```

I can see that there's an `ArrowDataType::Date32(Day)` enum variant in the docs at https://docs.rs/polars/0.9.0/polars/datatypes/enum.ArrowDataType.html, so I'm wondering if this is just a Parquet reading issue.

**Comment by ritchie46** [comment]
Hey Dave.. The Data32 type is indeed supported. Polars uses the parquet reader implemented in the `arrow` crate. That crate doesn't yet support `Date32`. Once they do, Polars does.
