### ISSUE TITLE
How to create a dataframe from an ndarray?

### ISSUE THREAD

**Issue by ErikDeSmedt** [ritchie46/polars#213]
The DataFrame API currently support conversion from a frame to an ndarray. Has the opposite conversion been implemented already?

**Comment by ritchie46** [comment]
Hi Erik, you can create `ChunkedArrays` from iterators. So you can do something like this in pseudo rust:

```rust
let ca: ChunkedArray<T> = ndarray.iter().map(Some).collect()

my_new_df.hstack(vec![ca.into_series()])
```
