### ISSUE TITLE
could not find `parquet` in `ser`

### ISSUE THREAD

**Issue by sa-** [ritchie46/polars#217]
I can't seem to import the parquet reader.

According to https://docs.rs/polars/0.9.0/polars/frame/ser/parquet/index.html, the parquet reader should be included in prelude, but it's not.

So when I try to import it using the path from this doc... 
https://docs.rs/polars/0.9.0/polars/frame/ser/parquet/struct.ParquetReader.html
`use polars::frame::ser::parquet::ParquetReader;`

I get this error
```
use polars::frame::ser::parquet::ParquetReader;
                        ^^^^^^^ could not find `parquet` in `ser`
unresolved import `polars::frame::ser::parquet`
```

**Comment by sa-** [comment]
Jupyter tab completion doesn't show parquet either: 
<img width="319" alt="image" src="https://user-images.githubusercontent.com/1297369/102107187-bec78b00-3e31-11eb-8084-4572e73ffd6a.png">

Even though I can see the file exists: https://github.com/ritchie46/polars/blob/master/polars/src/frame/ser/parquet.rs

**Comment by ritchie46** [comment]
the feature `"parquet"` is not one of the default features. You should add it to your `Cargo.toml`

```toml
polars = {version= "0.9.0", features = ["parquet", "simd", "lazy", "strings", "temporal", "random"]}
```

**Comment by sa-** [comment]
Cool, that fixed it, thanks!
