### ISSUE TITLE
Disable certain datatype behind feature flag to speed up compile time.

### ISSUE THREAD

**Issue by zirconium-n** [ritchie46/polars#218]
Compiling time is getting too long. And memory usage while linking is so large that I'm getting OOM error.
Is it possible to selective disable certain datatype behind feature flag?

**Comment by ritchie46** [comment]
Yes.. I was already planning this, as there are datatypes mirrored from Arrow, that don't really have a function yet. There is already a compile time issue. I am gonna close this in favor of #157
