### ISSUE TITLE
implement skip for iterators

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#236]

**Comment by marioloko** [comment]
Why do you want to re implement `skip` for iterators? The `skip` method is a provided method for the `Iterator` trait, as shown [here](https://doc.rust-lang.org/src/core/iter/traits/iterator.rs.html#1135-3286), then, implementing the trait would be enough to have the `skip` method available.

**Comment by ritchie46** [comment]
Looking at the source code of the Iterator trait, it seems that `skip` actually wraps around `nth`. I want to implement that for ChunkedIterators that are not a wrapper around `slice`. 

I believe the `nth` iterator just consumes the iterator by calling `next` multiple times` This will be a lot more expensive than just updating the `idx` values that point to the iterator state. 

A snippet that is called by `nth`:

```rust
  #[inline]
    #[unstable(feature = "iter_advance_by", reason = "recently added", issue = "77404")]
    fn advance_by(&mut self, n: usize) -> Result<(), usize> {
        for i in 0..n {
            self.next().ok_or(i)?;
        }
        Ok(())
    }

```

The reason I want to implement them is because in the Python wrappers I call lambda's untill the first non null value is returned. Then later I create another iterator and **skip** the number of values that are already consumed. This may be needlessly expensive in current implementation.

**Comment by marioloko** [comment]
Aha, I understand why you want a dedicated implementation of ’skip’. 

However, for the use case you mention, would not be better to use ’skip_while’ to discard the values in the iterator while they are null?

**Comment by ritchie46** [comment]
Yes, I do that while calling a custom lambda (defined by a user). When I obtain the first non-null output, I send the `usize` count, (that defines the number or of items seen) to another function which reinitializes the iterator. That's when I use skip. 

There will probably more edge cases where you want to skip `n` values of an iterator. It would be nice if that be a **O(1)** operation.

**Comment by marioloko** [comment]
Ok, undestoods.

I see that the `advance_by` method you posted is the eager implementation of `skip`, while `skip` is the lazy. By implementing `advance_by` with complexity **O(1)**, we get both implementations, the eager, the lazy and other functions like `nth`, with this complexity **O(1)**.

So I think we should target the function `advance_by` instead of `skip`.

**Comment by marioloko** [comment]
Most of the iterators keep the state `idx_left` and `idx_right`. This makes it easy the implementation of this functions. 

However, the numeric iterators, use arrow iterators instead, and in particular the `NumIterSingleChunk` iterator does not keep state of its `idx_left` and `idx_right` so they probably require a modification to include and update these values.

**Comment by ritchie46** [comment]
Yes, you are right that `skip` is the wrong target. Only `advance_by` is still nightly only (And I would really like to go to stable once arrow is stable). 

So I think `nth` is the next best thing.

> However, the numeric iterators, use arrow iterators instead, and in particular the NumIterSingleChunk iterator does not keep state of its idx_left and idx_right so they probably require a modification to include and update these values.

Pherhaps we could gradually implement that feature.

**Comment by marioloko** [comment]
Yes, I think that the way to go is to implement `advance_by` as a struct method and not like an `Iterator` method, and implement `nth` based on this method. This way the method would not be `unstable` and once the feature is moved to `stable` the only requirement will be to move the method to `Iterator`.

Check [this gist](https://gist.github.com/rust-play/8fb411280faaa38fb891b1274a670bfa) to clarify.

**Comment by ritchie46** [comment]
Ah, nice trick! I wouldn't have thought of that.

**Comment by ritchie46** [comment]
added #246
