### ISSUE TITLE
 Rows count error

### ISSUE THREAD

**Issue by Roodgerr** [ritchie46/polars#242]
When using polars dataframe for a predicate in the lgbm model, this error occurs.

'ValueError: Found input variables with inconsistent numbers of samples'
![image](https://user-images.githubusercontent.com/69750481/103310734-1a9d3100-4a3a-11eb-82a0-b959f7546578.png)

Why does sklearn read columns as rows?
![image](https://user-images.githubusercontent.com/69750481/103310795-46b8b200-4a3a-11eb-9a3f-fecf8d9495cf.png)

**Comment by ritchie46** [comment]
Polars indexing semantic don't exactly match those of numpy. Sklearn expects numpy arrays as input. To make your model train you can conver the DataFrame to a numpy array:

```
df["features"].to_numpy()
```

**Comment by Roodgerr** [comment]
Thank you for solving
