### ISSUE TITLE
Segmentation fault when reading biggish data

### ISSUE THREAD

**Issue by jangorecki** [ritchie46/polars#260]
When reading 50GB csv (1e9 rows) in groupby benchmark of db-benchmark script, python terminates with segfault
```
# groupby-polars.py
loading dataset G1_1e9_1e2_0_0
Segmentation fault
```
It occurs for all 5 datasets of 1e9 rows (G1_1e9_1e2_0_0, G1_1e9_1e1_0_0, G1_1e9_2e0_0_0, G1_1e9_1e2_0_1, G1_1e9_1e2_5_0).

**Comment by ritchie46** [comment]
Thanks for the heads up Jan. It's good that I do this benchmark, otherwise I would have never known on my 16 GB machine. :sweat_smile:

**Comment by jangorecki** [comment]
Segfaults also happens for join 1e9 data. Note that for join it would raise OOM error anyway later on (unless having mmap).

**Comment by ritchie46** [comment]
I expect the root cause is upstream in arrow. I use `utf8` datatype for strings. This stores all the bytes of the string data concatenated in a single array and stores another array of `i32` values as index in the byte array. It's very likely that the 1e9 rows exceed the 32 bit signed integer offset capacity (it happens already with avg strings slightly larger than 2 bytes.)

I will need to refactor to using `large_utf8` datatype. This uses a 64 bit signed integer in the offset array.

> Segfaults also happens for join 1e9 data. Note that for join it would raise OOM error anyway later on (unless having mmap).

Joins are in-memory, so that would be an OOM error I think.

**Comment by ritchie46** [comment]
#265 includes supporting large utf8 and large lists. Next benchmark run we'll know if this worked.

**Comment by jangorecki** [comment]
Do you know how much time it takes for release to land on pypi?

**Comment by ritchie46** [comment]
It's already patched! :)

**Comment by jangorecki** [comment]
For groupby segfault is fixed and now I got this
```
thread '<unnamed>' panicked at 'range end index 8 out of range for slice of leng
th 0', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-2.0.0/
src/array/builder.rs:937:26
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "./polars/groupby-polars.py", line 25, in <module>
    x = pl.read_csv(src_grp, dtype={"id4":pl.Int32, "id5":pl.Int32, "id6":pl.Int
32, "v1":pl.Int32, "v2":pl.Int32, "v3":pl.Float64})
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/
pypolars/functions.py", line 85, in read_csv
    dtype=dtype,
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/
pypolars/frame.py", line 131, in read_csv
    dtype,
pyo3_runtime.PanicException: range end index 8 out of range for slice of length 
0
```
for join it still segfaults

**Comment by ritchie46** [comment]
Ok. I will hire a bigger machine and sort this out. Thanks for your time so far.

**Comment by ritchie46** [comment]
> For groupby segfault is fixed and now I got this
> 
> ```
> thread '<unnamed>' panicked at 'range end index 8 out of range for slice of leng
> th 0', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-2.0.0/
> src/array/builder.rs:937:26
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Traceback (most recent call last):
>   File "./polars/groupby-polars.py", line 25, in <module>
>     x = pl.read_csv(src_grp, dtype={"id4":pl.Int32, "id5":pl.Int32, "id6":pl.Int
> 32, "v1":pl.Int32, "v2":pl.Int32, "v3":pl.Float64})
>   File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/
> pypolars/functions.py", line 85, in read_csv
>     dtype=dtype,
>   File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/
> pypolars/frame.py", line 131, in read_csv
>     dtype,
> pyo3_runtime.PanicException: range end index 8 out of range for slice of length 
> 0
> ```
> 
> for join it still segfaults

Do you happen to know on which of the 5 datasets this happened?

**Comment by jangorecki** [comment]
all 5 has same error

**Comment by ritchie46** [comment]
That's interesting. :thinking:  

I ran G1_1e9_1e2_5_0 successfully. There was a memory peak of 180GB so it would not have finished on the 125GB node. When the next run is scheduled could you set `RUST_BACKTRACE=1`?

**Comment by jangorecki** [comment]
```
# groupby-polars.py
loading dataset G1_1e9_1e2_5_0
thread '<unnamed>' panicked at 'range end index 8 out of range for slice of length 0', /github/home/.cargo/registry/src/github.com-1ecc6299db9ec823/arrow-2.0.0/src/array/builder.rs:937:26
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Traceback (most recent call last):
  File "polars/groupby-polars.py", line 25, in <module>
    x = pl.read_csv(src_grp, dtype={"id4":pl.Int32, "id5":pl.Int32, "id6":pl.Int32, "v1":pl.Int32, "v2":pl.Int32, "v3":pl.Float64})
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/pypolars/functions.py", line 85, in read_csv
    dtype=dtype,
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/pypolars/frame.py", line 131, in read_csv
    dtype,
pyo3_runtime.PanicException: range end index 8 out of range for slice of length 0
```

```
# groupby-polars.py
loading dataset G1_1e9_1e2_5_0
thread '<unnamed>' panicked at 'range end index 8 out of range for slice of length 0', /github/home/.cargo/registry/src/github.com-1
ecc6299db9ec823/arrow-2.0.0/src/array/builder.rs:937:26
stack backtrace:
   0:     0x7f4e52b0c940 - <unknown>
   1:     0x7f4e52b32afc - <unknown>
   2:     0x7f4e52b09822 - <unknown>
   3:     0x7f4e52b0edd5 - <unknown>
   4:     0x7f4e52b0ea78 - <unknown>
   5:     0x7f4e52b0f571 - <unknown>
   6:     0x7f4e52b0f0b7 - <unknown>
   7:     0x7f4e52b0cddc - <unknown>
   8:     0x7f4e52b0f019 - <unknown>
   9:     0x7f4e52b302e1 - <unknown>
  10:     0x7f4e52b347c2 - <unknown>
  11:     0x7f4e529d606e - <unknown>
  12:     0x7f4e529d6246 - <unknown>
  13:     0x7f4e52208040 - <unknown>
  14:     0x7f4e51dbd27c - <unknown>
  15:     0x7f4e5251b7eb - <unknown>
  16:     0x7f4e522a8ad6 - <unknown>
  17:     0x7f4e521b61ce - <unknown>
  18:     0x7f4e51b061c5 - <unknown>
  19:     0x7f4e51b56493 - <unknown>
  20:     0x7f4e519065f0 - <unknown>
  21:     0x7f4e51b5de27 - <unknown>
  22:           0x5243cb - _PyCFunction_FastCallKeywords
  23:           0x57e7d9 - <unknown>
  24:           0x576f9f - _PyEval_EvalFrameDefault
  25:           0x57609f - <unknown>
  26:           0x57f96b - <unknown>
  27:           0x57e8bc - <unknown>
  28:           0x577c17 - _PyEval_EvalFrameDefault
  29:           0x57609f - <unknown>
  30:           0x57f96b - <unknown>
  31:           0x57e8bc - <unknown>
  32:           0x577c17 - _PyEval_EvalFrameDefault
  33:           0x57609f - <unknown>
  34:           0x575e13 - PyEval_EvalCode
  35:           0x5eb302 - <unknown>
  36:           0x5eb76a - PyRun_FileExFlags
  37:           0x5eb527 - PyRun_SimpleFileExFlags
  38:           0x5f0a33 - Py_Main
  39:           0x4d2e09 - main
  40:     0x7f4e53779840 - __libc_start_main
  41:           0x5e8d69 - _start
  42:                0x0 - <unknown>
Traceback (most recent call last):
  File "polars/groupby-polars.py", line 25, in <module>
    x = pl.read_csv(src_grp, dtype={"id4":pl.Int32, "id5":pl.Int32, "id6":pl.Int32, "v1":pl.Int32, "v2":pl.Int32, "v3":pl.Float64})
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/pypolars/functions.py", line 85, in read_csv
    dtype=dtype,
  File "/home/jan/git/db-benchmark/polars/py-polars/lib/python3.6/site-packages/pypolars/frame.py", line 131, in read_csv
    dtype,
pyo3_runtime.PanicException: range end index 8 out of range for slice of length 0
```

**Comment by ritchie46** [comment]
@jangorecki I saw there was a rerun and that the csv was at least parsed without a segfault. Can you confirm it segfaulted again (and that the visual is not correctly updated), or was it an OOM?

**Comment by jangorecki** [comment]
When loading data it got
```
RuntimeError: Any(Other("Other(\"Could not parse primitive type during csv parsing: Error { code: In
validDigit, index: 2 }\") on thread line 7; on inp
ut: 33.981703"))
```

**Comment by jangorecki** [comment]
Same error occurs to 1e7 and 1e8 data with NAs, so problem is now about missing values.

**Comment by jangorecki** [comment]
Non NA data case for 1e9 passes fine up to Q10 where process is killed by OOM

**Comment by ritchie46** [comment]
Great! thanks for the info. :+1:
