### ISSUE TITLE
Panic: not an agg expression

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#269]
Ran into this panic when doing:

```rust
            .with_columns(vec![
                col("date").map(|s: Series| s.hour(), Some(UInt32)).alias("hour"),
                col("date").map(|s: Series| s.minute().map(|m| m / 5), Some(UInt32)).alias("minute"),
            ])
            .groupby(&["hour", "minute"])
            .agg(vec![
                col("date").first(),
                col("hour"),
                col("minute"),
            ])
```

```
thread '<unnamed>' panicked at 'not an agg expression', C:\Users\dkolsoi\.cargo\registry\src\github.com-1ecc6299db9ec823\polars-
0.11.1\src\lazy\physical_plan\mod.rs:44:9
```

**Comment by TheDan64** [comment]
I think this is because `col("hour")` & `col("minute")` aren't valid here but it seems like it should return a result rather than panicking?

**Comment by ritchie46** [comment]
This is the start of a downsample function :smile: !

Correct, it's due to the `col()` without any aggregations. The keys are automatically added to your result, so only thing you'd need would be:

```rust
            .with_columns(vec![
                col("date").map(|s: Series| s.hour(), Some(UInt32)).alias("hour"),
                col("date").map(|s: Series| s.minute().map(|m| m / 5), Some(UInt32)).alias("minute"),
            ])
            .groupby(&["hour", "minute"])
            .agg(vec![
                col("date").first(),
            ])
```

In the next release/master you can directly group by on expressions. That would be:
```rust
            .groupby(vec![
                col("date").map(|s: Series| s.hour(), Some(UInt32)).alias("hour"),
                col("date").map(|s: Series| s.minute().map(|m| m / 5), Some(UInt32)).alias("minute"),
            ])
            .agg(vec![
                col("date").first(),
            ])
```

But on the `panic!`... I've been thinking about what is correct. Currently Polars allows to panic when a query is flawed/incorrect.

**Comment by TheDan64** [comment]
Got it - I suppose panicing isn't awful since it's sort of an edge case programmer error? At the very least the panic message could be improved to add more information, like which expr is panicing, so that it's easier to find and remove/fix it

The alternative might be for some sorta builder pattern that stores the first error it finds and propagates it at the end: `lazy.build().groupby(...).agg(...).finalize()?` though that seems like a big change
