### ISSUE TITLE
LazyFrame::with_column_renamed doesn't remove original column

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#270]
`DataFrame::rename` will remove the original column and add the newly named one (as expected), however, `LazyFrame::with_column_renamed` will leave the original in place which is unexpected (v0.11.1)

**Comment by ritchie46** [comment]
You are right. I will look into that. The best practice is to use a `select` at the end of your query. This will optimize your query for the columns you need and will make sure that intermediate columns are removed at their nodes.

**Comment by TheDan64** [comment]
Good to know, thanks!
