### ISSUE TITLE
Display impl for DataFrame is incorrect

### ISSUE THREAD

**Issue by lwiklendt** [ritchie46/polars#277]
When the number of columns is larger than `max_n_columns` then the first `max_n_columns` is displayed with a superfluous `"..."` column inserted as the middle column, and columns `max_n_columns..self.width()` are omitted. Expected behaviour is the first `max_n_columns/2` columns and the last `max_n_columns/2` columns are displayed with a `"..."` column between them.

**Comment by ritchie46** [comment]
:+1:
