### ISSUE TITLE
Set list of columns as argument in read_csv()

### ISSUE THREAD

**Issue by r-brink** [ritchie46/polars#281]
At the moment it is not possible to set a list of column names for a Dataframe when reading in a csv. You have to read in the csv first and after that you have to set the column names.

```python
column_names =  ['foo', 'bar']

df = pl.read_csv('file.csv')
df.columns = column_names
```

Ideally you would set the columns names while reading in the csv, similar to the functionality that pandas offers.
```python
column_names =  ['foo', 'bar']

df = pl.read_csv('file.csv', column_names=column_names)
```

**Comment by ritchie46** [comment]
Ho should it deal with arguments that have a different length? Only overwrite the columns that are given in that order?
