### ISSUE TITLE
Process strings with rust

### ISSUE THREAD

**Issue by 1138886114** [ritchie46/polars#287]
Python's method，
https://ritchie46.github.io/polars-book/how_can_i/process_strings.html

I can't use it in trust according to the method of Python. I've turned on the string feature in toml。

**Comment by 1138886114** [comment]
Who can write a sample code, I am very grateful

**Comment by ritchie46** [comment]
I assume you want to use string utilities in Rust?

If you have series you need to downcast it to a `ChunkedArray` to use the string processings. Something like this:

```rust
fn example(s: Series) -> Result(ChunkedArray<Utf8Type>) {
    Ok(s.utf8()?.to_lowercase())
}
```

**Comment by ritchie46** [comment]
Don't see much activity so I am closing this.
