### ISSUE TITLE
Join on a float field fails

### ISSUE THREAD

**Issue by keiv-fly** [ritchie46/polars#295]
When executing a join with a float field as key the join fails in Rust code (panic exception)

pypolars=='0.4.5'

Here is a very short example that fails:
```
>>> import pypolars as pl
>>> import numpy as np
>>>
>>> ldf1 = pl.DataFrame({"id":[0.0,1.0, np.nan],"data":["a","b","c"]})
>>> ldf2 = pl.DataFrame({"id":[0.0,1.0],"data2":["b","c"]})
>>> ldf1.join(ldf2, on="id")
thread '<unnamed>' panicked at 'not implemented', polars\polars-core\src\frame\hash_join.rs:302:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\serge\anaconda3\lib\site-packages\pypolars\frame.py", line 606, in join
    out = self._df.join(df._df, left_on, right_on, how)
pyo3_runtime.PanicException: not implemented
```

**Comment by ritchie46** [comment]
yes.. That is currently the expected behavior. Floating point values cannot trivially be compared. 

For now the recommended method for joining is casting to integers. If you lose precision due to this you can first multiply with `1e3`, `1e6` or whatever precision you require.

**Comment by keiv-fly** [comment]
If I cast to integer then I get "implementation error, cannot get ref Int64 from Float64"

```
>>> ldf1 = pl.DataFrame({"id":[0.0,1.0, np.nan],"data":["a","b","c"]})
>>> ldf1["id"] = ldf1["id"].cast(int)
>>> ldf2 = pl.DataFrame({"id":[0.0,1.0],"data2":["b","c"]})
>>> ldf1.join(ldf2, on="id")
thread '<unnamed>' panicked at 'implementation error, cannot get ref Int64 from Float64', polars\polars-core\src\series\implementations.rs:45:13
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\serge\anaconda3\lib\site-packages\pypolars\frame.py", line 606, in join
    out = self._df.join(df._df, left_on, right_on, how)
pyo3_runtime.PanicException: implementation error, cannot get ref Int64 from Float64
```

**Comment by keiv-fly** [comment]
Also:
> Floating point values cannot trivially be compared.
I thought that if both fields are float64 then they can be easily compared bit by bit.

Anyways, my main issue is that I have NAs. I was just experimenting doing left joins faster than in pandas and was manually converting a string field to integers. I got down from 25 seconds doing joins with string in pandas to 15 seconds with joins using integers in pandas. Pypolars does it in 5 seconds, but I have to manually delete the NA lines and convert the indices to integers. I can neither use float64 nor a nullable pd.Int64Dtype, which is very inconvenient.

**Comment by keiv-fly** [comment]
I figured out that I fogot to convert the other field to int. With this one it works:
```
ldf1 = pl.DataFrame({"id":[0.0,1.0, np.nan],"data":["a","b","c"]})
ldf1["id"] = ldf1["id"].cast(int)
ldf2 = pl.DataFrame({"id":[0.0,1.0],"data2":["b","c"]})
ldf2["id"] = ldf2["id"].cast(int)
ldf1.join(ldf2, on="id")
```

**Comment by ritchie46** [comment]
Great! 

In the groupby logic we decode a floating point values in the mantissa and the exponent. Later I will add this funcitonality for joins.
