### ISSUE TITLE
select_all_except

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#313]
So I've started building LazyFrame pipelines that seamlessly flow one into another. It'd be nice to have a select at the end of each pipeline so that I can get rid of temporary columns. The problem is, each pipeline isn't usually aware of every column it should keep, only aware of every column it should get rid of. Therefore it'd be useful to have a `lf.select_all_execpt(&["col1", "col2"])` which keeps everything except the provided column names

**Comment by ritchie46** [comment]
Hi @TheDan64 , See PR #316
