### ISSUE TITLE
The function cast_with_data_type in examples/aggregate_multiple_files_in_chunks/src/main.rs does not work

### ISSUE THREAD

**Issue by Mick1406** [ritchie46/polars#324]
Hi,

First, thanks for this awesome library! 

Working from your example in examples/aggregate_multiple_files_in_chunks/src/main.rs, the code does not run '__as is__' . 

1) The  `cast_with_data_type` function does not exist anymore. It looks like it's been replaced with __`cast_with_datatype`__

2) In the get_schema function, the following does not work and return errors.
```
        Field::new("category", ArrowDataType::Utf8, false),
        Field::new("calories", ArrowDataType::UInt64, false),
        Field::new("fats_g", ArrowDataType::Float64, false),
        Field::new("sugars_g", ArrowDataType::Float64, false),
```
I was able to get around with the following, but (being very new to Rust) I am not sure that this is correct:
```
        Field::new("category", polars::prelude::DataType::List(ArrowDataType::Utf8)),
        Field::new("calories", polars::prelude::DataType::List(ArrowDataType::UInt64)),
        Field::new("fats_g", polars::prelude::DataType::List(ArrowDataType::Float64)),
        Field::new("sugars_g", polars::prelude::DataType::List(ArrowDataType::Float64)),
```

**Comment by ritchie46** [comment]
Hi Mick, your code is correct. :)
