### ISSUE TITLE
Stable compiler plans?

### ISSUE THREAD

**Issue by jmrgibson** [ritchie46/polars#326]
With the merge of https://issues.apache.org/jira/browse/ARROW-10002, it looks like it should be possible to run arrow on a stable compiler, which maybe means polars would work too? I tried disabling default features (specifically `simd`), but cargo still end up including `packed_simd_2-0.3.4` somehow, through the arrow->polars-core crate.

Is there something else I'm missing that would preclude me from using rust stable?

**Comment by ritchie46** [comment]
Thanks for noting!

As of #331, it must work.

**Comment by jmrgibson** [comment]
Awesome, thanks for the quick turnaround.
