### ISSUE TITLE
min()/max() behaves different with nan

### ISSUE THREAD

**Issue by elbaro** [ritchie46/polars#328]
```
>>> from math import nan
>>> pypolars.Series([1,2,3,4, nan])
Series: '' [f64]
[
	1
	2
	3
	4
	NaN
]
>>> pypolars.Series([1,2,3,4, nan]).max()
nan
>>> pypolars.Series([1,2,3,4, nan]).min()
1.0
```

**Comment by elbaro** [comment]
pandas use NaN to represent missing values. polars has None for this purpose, so I think both `max(NaN, 2, 3)=3` and `max(Nan, 2, 3)=NaN` make sense, as long as we are consistent with all aggregation functions.

**Comment by ritchie46** [comment]
Consistency indeed, and the possibility to ignore / include NaNs. I can imagine this is completely use case dependent.

**Comment by alamb** [comment]
> I can imagine this is completely use case dependent

That is likely, though I can't think of any usecase for an aggregate function like `min` or `max` to be null / nan if any of its inputs is null/nan 

`nan_mean` I can understand as you may want to adjust the denominator for total element count (not just non nan)

Sorting is a different story and you may be sorting on columns that have Nans in them but the other columns are non-null preserved
