### ISSUE TITLE
CsvWriter is broken with Utf8 column

### ISSUE THREAD

**Issue by zirconium-n** [ritchie46/polars#333]
Apparently arrow csv writer doesn't support LargeUtf8 column. With the change from using Utf8 to LargeUtf8, CsvWriter is broken.

Not saying using LargeUtf8 is wrong though.

polars ver: 0.12.0
arrow ver: 3.0.0

**Comment by ritchie46** [comment]
When this is merged into arrow it will be available here on master.

https://github.com/apache/arrow/pull/9426
