### ISSUE TITLE
Join panics

### ISSUE THREAD

**Issue by elbaro** [ritchie46/polars#334]
`df.join(..)` panics because it assumes columns have the same number of chunks but it does not.

Since `df.n_chunks()==1`, `take_opt_iter_unchecked_bounds` calls `take_from_single_chunked` for each column. However it panics on the column with `chunks().len()==2`.

A workaround is to call `df.rechunk()` before every join.

**Comment by ritchie46** [comment]
Yes.. The number of chunks in a DataFrame should be the same for all Series. This is checked upon entry of the DataFrame. Could you tell me what you did that led to this panic?

**Comment by ritchie46** [comment]
I believe you mentioned earlier that you used `DataFrame::add_column`.  I forgot to call `rechunk` there. It should now be fixed.

**Comment by elbaro** [comment]
```
let shifted = df.column("col")?; // col has 1 chunk
df.add_column(shifted)  // shifted has 2 chunks
df.join(.) // panics
```
