### ISSUE TITLE
Cannot change null values in Python

### ISSUE THREAD

**Issue by elbaro** [ritchie46/polars#338]
I am trying to replace null values but they are untouchable.

With mask:
```
>>> a = pypolars.Series([1,2,3,4,5]).shift(2)
>>> a
Series: '' [i64]
[
	null
	null
	1
	2
	3
]
>>> a[a.is_null()] = 100
>>> a
Series: '' [i64]
[
	null
	null
	1
	2
	3
]
```

With set()
```
>>> a.set(a.is_null(), 100)
Series: '' [i64]
[
	null
	null
	1
	2
	3
]
```

With apply()
```
>>> a.apply(lambda _: 100)
Series: '' [i64]
[
	null
	null
	100
	100
	100
]
```

If these behaviors are intended, how can I change nulls?
Also how to manually assign null to a specific index (like `a[4]=null`)?

**Comment by ritchie46** [comment]
Right, this is because the null values are ignored and later applied. However when the mask is set on the null values. This is unwanted behavior. I will look into it, thanks.
