### ISSUE TITLE
Pandas datetime conversion to py-polars

### ISSUE THREAD

**Issue by Tian-Le97** [ritchie46/polars#340]
I am currently exploring Py-Polars and are having some difficulties with getting the Date32 format in its dataframe. I have tried the following means:

1. Conversion from Pandas to PyPolars directly
```
import pandas as pd
import pypolars as pyp

a = pd.read_csv(*CSV File*)
b = pyp.from_pandas(a)
```
The error code is as follows:

```
Traceback (most recent call last):
  File "<pyshell#29>", line 1, in <module>
    pyp.from_pandas(a)
  File "C:\Users\*UserName*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\functions.py", line 235, in from_pandas
    pl_s = Series(k, s, nullable=True).cast(datatypes.Date64)
  File "C:\Users\*UserName*\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\series.py", line 783, in cast
    return wrap_s(f())
RuntimeError: Any(ArrowError(ComputeError("Casting from Int32 to Date64 not supported")))
```
2. Conversion DateTime to String in Pandas, convert to PyPolars, converting String to DateTime in PyPolars

```
def changeDateTime(value):
    return str(value)

a["ACTUAL_DROP_DATE"] = a["ACTUAL_DROP_DATE"].apply(changeDateTime)
a["ACTUAL_END_DATE"] = a["ACTUAL_END_DATE"].apply(changeDateTime)

b = pyp.from_pandas(a)

def changeStrBack(value):
    if value == np.str("NaT"):
        return ""
    else:
        year = int(value[0:4])
        month = int(value[5:7])
        day = int(value[8:10])
        return pyp.datetime(year, month, day)

b["ACTUAL_DROP_DATE"] = b["ACTUAL_DROP_DATE"].apply(changeStrBack, dtype_out = pyp.Date32)
b["ACTUAL_END_DATE"] = b["ACTUAL_END_DATE"].apply(changeStrBack, dtype_out = pyp.Date32)
```
This has thrown me all the null values upon conversion. (i.e. both columns are completely null).

Hope anyone have some ideas on how I can get the columns to datetime in PyPolars.

Thank you!

**Comment by ritchie46** [comment]
Hi, Could you show me some of your data, so I can take a look?

**Comment by Tian-Le97** [comment]
]

> Hi, Could you show me some of your data, so I can take a look?

Hi, sure! This is the two datetime column of my dataset.
![image](https://user-images.githubusercontent.com/42717379/107038048-ee25c300-67f6-11eb-9aaf-6eda35d46d34.png)

**Comment by ritchie46** [comment]
And if you could give me a snippet I could copy+paste it would be even better! ;)

**Comment by Tian-Le97** [comment]
[finaldata.zip](https://github.com/ritchie46/polars/files/5933863/finaldata.zip)

I have provided you with the complete dataset I have used, it should be much easier for you to read in directly :)

**Comment by ritchie46** [comment]
Hmm.. I cannot open that file. It seems to be a binary sas file?

**Comment by ritchie46** [comment]
Hi @Tian-Le97 , Your function `changeStrBack` is incorrect use of `py-polars`. To cast a `string` to a date object, you can choose between a:

* Date -> `Date32`
* Datetime -> `Date64`

You can load the DataFrame and later cast the string columns.

# Example

```python
df = pl.DataFrame({
    "a": ["2007-01-01"] * 10,
    "b": ["2007-01-01"] * 10,
})
df
```
```text
shape: (10, 2)
╭──────────────┬──────────────╮
│ a            ┆ b            │
│ ---          ┆ ---          │
│ str          ┆ str          │
╞══════════════╪══════════════╡
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ...          ┆ ...          │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ "2007-01-01" ┆ "2007-01-01" │
╰──────────────┴──────────────╯
```

```python
df["a"].str_parse_date(pl.Date32)
```

```text
Series: 'a' [date32]
[
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
	2007-01-01
]
```

**Comment by Tian-Le97** [comment]
Thank you for your reply, and providing me with an alternative solution. It is working well now, so really appreciate it! Would just like to check if there is no way of directly converting the datetime format using the first method? (i.e. Using pyp.from_pandas)

**Comment by ritchie46** [comment]
Yes.. That should work. If you can give me a minimal working example that reproduces your error, I can take a look.

**Comment by ritchie46** [comment]
In the new [pre-release](https://pypi.org/project/py-polars/0.6.0-alpha.1/) all these issues should be solved.

**Comment by Tian-Le97** [comment]
Hello! Actually, this does not seem to have resolved even with the latest version.

In the direct transforming from Pandas Dataframe, the following error code has been thrown:
`Traceback (most recent call last):
  File "<pyshell#34>", line 1, in <module>
    e = pyp.from_pandas(a)
  File "C:\Users\Tian Le\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\functions.py", line 278, in from_pandas
    return from_arrow_table(table)
  File "C:\Users\Tian Le\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\functions.py", line 252, in from_arrow_table
    return DataFrame.from_arrow(table, rechunk)
  File "C:\Users\Tian Le\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\frame.py", line 223, in from_arrow
    self._df = PyDataFrame.from_arrow_record_batches(batches)
pyo3_runtime.PanicException: arrow array: CDataInterface("The datatype \"{}\" is still not supported in Rust implementation")`

On the other hand, the method provided above seems to have failed now, while it was working previously - now showing the error:
`Traceback (most recent call last):
  File "<pyshell#30>", line 1, in <module>
    d["ACTUAL_DROP_DATE"] = d["ACTUAL_DROP_DATE"].str_parse_date(pyp.Date32)
  File "C:\Users\Tian Le\AppData\Local\Programs\Python\Python37\lib\site-packages\pypolars\series.py", line 1136, in str_parse_date
    return wrap_s(self._s.str_parse_date32(fmt))
RuntimeError: Any(Other("Could not find an appropriate format to parse dates, please define a fmt"))`

Hope to seek your kind help! I would love to provide you with an example (I am working mainly with sas7bdat files), but it seems like reading in CSV/Excel file into Pandas recognise dates as strings, which defeat the purpose.

**Comment by ritchie46** [comment]
The second error message hints to the solution. ;) `"Could not find an appropriate format to parse dates, please define a fmt"`. You need to define a [fmt](https://docs.rs/chrono/0.4.7/chrono/format/strftime/index.html) string so that Polars knows how to parse the string column.

For the first error message I really need an example with a small DataFrame with something like 3 datapoints that reproduce that error.
