### ISSUE TITLE
Support for reading Feather format.

### ISSUE THREAD

**Issue by ghuls** [ritchie46/polars#36]
It looks like polars is still in early stages, so it might be too soon for this feature request, but it would be nice if polars can read and write Dataframes to Apache Arrow Feather format.

I currently have some pandas code that reads a Feather file with 25000 columns and 1 milion rows (of float32 ==> 93 GB) on which I need to apply a function on each column:
  - create a random permutation of the same length as the number of rows
  - read a column but access the elements in the order created in the random permutation step (this is to make sure than when argsorting later that tied scores that appear more to the top of the column are not ranked higher
  - argsort that array in reverse
  - undo the random permutation step on the previous array (so we have a ranking for the input column) 

The problem with pandas is that `pd.read_feather` consolidates the data (so it makes a memory copy) as it stores all data in a big numpy array, while Feather should be zero copy, so if polars would support zero copy operations on feather files, it would be great.

As far as I can see, `argsort` is recently implemented.
I guess the zero copy numpy view would be important too.

```python
import pandas as pd

df_scores__motifs_vs_regions_or_genes = pd.read_feather('motifs_vs_regions_or_genes.scores.feather')

def rank_CRM_scores_and_assign_random_ranking_in_range_for_ties_func(crm_scores_with_ties_for_motif_numpy):
            # Create random permutation so tied scores will have a different ranking each time.
            random_permutations_to_break_ties_numpy = np.random.permutation(crm_scores_with_ties_for_motif_numpy.shape[0])

            rank_column_with_broken_ties_numpy = random_permutations_to_break_ties_numpy[
                (-crm_scores_with_ties_for_motif_numpy)[random_permutations_to_break_ties_numpy].argsort()
            ].argsort().astype(np.int32)

            return rank_column_with_broken_ties_numpy

# Create feature table ranking.
df_ranking__motifs_vs_regions_or_genes = df_scores__motifs_vs_regions_or_genes.apply(
    rank_CRM_scores_and_assign_random_ranking_in_range_for_ties_func,
    axis='index',
    raw=True
)


df_ranking__motifs_vs_regions_or_genes.reset_index(inplace=True)

df_ranking__motifs_vs_regions_or_genes.to_feather(path='motifs_vs_regions_or_genes.rankings.feather')
```

**Comment by ritchie46** [comment]
As I understand it feather will be replaced by Arrow IPC. 

https://issues.apache.org/jira/browse/ARROW-4463 

IPC will be supported. For most file (de)serialization I will use arrows upstream implementation, so I they support it Polars will,

**Comment by ghuls** [comment]
Thanks. If Arrow IPC will be supported, that would be very useful.

**Comment by ritchie46** [comment]
An Arrow IPC Reader and Writer is added in 22fdc78b961d71e8e23e8bef8271e4299e1739dd
