### ISSUE TITLE
can‘t compile polars newest version

### ISSUE THREAD

**Issue by CHCP** [ritchie46/polars#363]
Hi there,
   I just want to test polars  for my product, but there are some compile errors, any components I missed? Would you please give me a hand, thanks.

```
[Cargo.toml]
#polars
polars  = "0.12.1"
```

```
cargo build:

error[E0554]: `#![feature]` may not be used on the stable release channel
   --> C:\Users\Gordon\.cargo\registry\src\github.com-1ecc6299db9ec823\packed_simd_2-0.3.4\src\lib.rs:202:1
    |
202 | / #![feature(
203 | |     repr_simd,
204 | |     rustc_attrs,
205 | |     const_fn,
...   |
215 | |     llvm_asm
216 | | )]
    | |__^

```

**Comment by ritchie46** [comment]
Hi @CHCP, for the latest release on crates.io you still need a nightly compiler. The current master version runs on stable and only requires nightly if you want to enable SIMD.

**Comment by CHCP** [comment]
Hi @ritchie46 
  Thanks ritchie46, it is works when I switch toolchain to nightly.

 Regards
