### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by jangorecki** [ritchie46/polars#368]
Hi Ritchie,
Maybe it is there but I just don't know where to look for it. Do you have a NEWS file or any other kind of changelog file? so it is easier to follow what have changed in each release.

**Comment by ritchie46** [comment]
I did that in the Rust library, but I stopped doing that when it got more inner restructuring/ stabilizing instead of features. However, you are right that I should better communicate changes. I'll see if I at least can log PR's and make a summary.

**Comment by ritchie46** [comment]
Is added and maintained.
