### ISSUE TITLE
Issue with as_result! macro

### ISSUE THREAD

**Issue by jakehubbard** [ritchie46/polars#373]
While I was reading your '10 minutes to Polars'. I came across an error while trying to execute the as_result! macro. I am using a jupyter notebook just like in the '10 minutes to Polars'

I defined the Dataframe _df_ just like in the guide.

```
let dates = &[
    "2020-08-21",
    "2020-08-21",
    "2020-08-22",
    "2020-08-23",
    "2020-08-22",
];
let fmt = "%Y-%m-%d";
let s0 = Date32Chunked::parse_from_str_slice("dates", dates, fmt).into();
let s1 = Series::new("n", &[1, 2, 3, 4, 5]);
let s2 = Utf8Chunked::full("foos", "foo", 5).into();

let df = DataFrame::new(vec![s0, s1, s2]).expect("something went wrong");
df
```
Then I defined the macro _as_result!_ according to the documentation (master branch).

```
#[macro_use]
macro_rules! as_result {
    ($block:block) => { ... };
}
```
I then tried to perform the boolean indexing on _df_ using _as_result!_.

```
as_result!({
    // select the n column
    let n_s = df.column("n")?;
    
    // create the boolean mask
    let mask = (n_s.gt(2) & n_s.lt(5))?;

    // filter values > 2
    df.filter(&mask)
}).unwrap()
```
Which returned the error

```
unexpected token: `...`
help: use `..` for an exclusive range

..
help: or `..=` for an inclusive range

..=


inclusive range with no end
help: use `..` instead

..
```

I changed the _as_result!_ macro to use `{ .. }` instead like the compiler suggested but ended up with a different error

```
}).unwrap()
   ^^^^^^ method not found in `RangeFull`
no method named `unwrap` found for struct `RangeFull` in the current scope
```

Let me know what I am doing wrong here. This is an excellent library. Thank you for your hard work. 

Also the guide is still using the deprecated `df.columns()` for listing column names instead of  `df.get_column_names()`

**Comment by ritchie46** [comment]
Hi jake, you macro is now a Rust range `{ .. }`. You probably need a macro like this:

```rust
macro_rules! as_result {
    ($block:block) => {{
        let res: Result<_> = $block;
        res
    }};
}
```

However, the notebook is quite old, so I expect that there are more issues than that one. I would recommend using an IDE that supports `rust-analyzer` or something similar as the type inference in the jupyter notebooks were hard to debug in my opinion.
