### ISSUE TITLE
[Python] Utilize numpy ufunc

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#38]
Series can be used by ufunc by using __array__ 
https://numpy.org/devdocs/user/basics.dispatch.html

Create an aligned array in the Rust heap and use numpy out keyword https://numpy.org/doc/stable/reference/ufuncs.html to write ufunc output to Rust. This buffer can be used to create an arrow array.

**Comment by ritchie46** [comment]
467c3c2eb1106b409750f09c985180bf84f095e5 We are able to get a view of the rust memory and use that as numpy array. We also allocate a 64 bit aligned buffer in Rust. From this buffer a numpy array is created and that is used to write the results of the `ufunc` to. 

Is this really zero copy? What does [PyArray_SetBaseObject](https://numpy.org/devdocs/reference/c-api/array.html#c.PyArray_SetBaseObject) do? Is it even possible to write to rust memory from numpy?

**Comment by ritchie46** [comment]
Keep null bitmask.

**Comment by ritchie46** [comment]
Discussion from the [Pyo3 Gitter](https://gitter.im/PyO3/Lobby)

![Selection_028](https://user-images.githubusercontent.com/3023000
/93306010-94990980-f7ff-11ea-8358-43e38ae5623d.png)
![Selection_029](https://user-images.githubusercontent.com/3023000/93306019-98c52700-f7ff-11ea-86d5-5fab6f7742bb.png)
![Selection_030](https://user-images.githubusercontent.com/3023000/93306023-9b278100-f7ff-11ea-8911-f8938e82fc55.png)
![Selection_032](https://user-images.githubusercontent.com/3023000/93306030-9cf14480-f7ff-11ea-99f4-3438483732bc.png)

**Comment by mindv0rtex** [comment]
I'd be curious to see your final solution for learning's sake!

**Comment by ritchie46** [comment]
> I'd be curious to see your final solution for learning's sake!
The gitter chat images are somewhat what is implemented. I still need to make it a bit more safe, as I am swapping pointers from Rust to Python and intentionally leak memory/ take memory to make it work. (Maybe a good one for an expert session ;))
