### ISSUE TITLE
Support reading/writing local/S3 path/URI/URL/file

### ISSUE THREAD

**Issue by impredicative** [ritchie46/polars#384]
I request that the various `read_` and `write_` functions, especially for CSV and parquet, consistently support all of the following inputs and outputs:

1. Path as string
2. Path as `pathlib.Path`
3. Path as file URI or AWS S3 URI. For example, pandas and [`smart_open`](https://github.com/RaRe-Technologies/smart_open) support both such URIs
4. HTTP URL, e.g. https://j.mp/iriscsv
5. Binary file object
6. Text file object (for CSVs) (not for parquet)

This will make reading and writing more streamlined, especially when working in the cloud with object stores.

**Comment by ritchie46** [comment]
Hi @impredicative,

Thanks for your feature request. I agree that py-polars should add functionality for paths (`pathlib` and `str`). I also agree with an in memory file like `io.BytesIO`. However for support of AWS or GCP, why not use `smart_open` for that? It seems to me that you combine the core purpose of `polars` (being a DataFrame lib), with the core purpose of `boto3`, or `smart_open`.

Current status:

- [x] Path as string
- [ ] Path as `pathlib.Path`
- [x] Binary file object
- [x] String file object

**Comment by impredicative** [comment]
@ritchie46 Why are "Binary file object" and "String file object" checked? Looking at the docs, [`to_parquet`](https://ritchie46.github.io/polars/pypolars/frame.html#pypolars.frame.DataFrame.to_parquet) doesn't currently support file objects. Can this be implemented? Without this I will have to write the file to ramdisk and then upload it using boto3, which would be tedious.

**Comment by ritchie46** [comment]
You are right, this isnt yet supported for all IO. I shall see that we can support bytes object for parquet, csv etc.

**Comment by impredicative** [comment]
Added HTTP URL to numbered list.

**Comment by ritchie46** [comment]
I will close this, since all these are implemented.

**Comment by jordan-carson** [comment]
Are there any examples or links on how to stream a dataframe to AWS S3?
