### ISSUE TITLE
rolling_min() returns wrong result

### ISSUE THREAD

**Issue by rubyfin** [ritchie46/polars#386]
It appears that rolling_min() is not calculated correctly, unless I am missing on the intent how this function should work.
Actually, i tested a few more rolling functions, and they all work in the same way, which I believe is incorrect.

**Steps to reproduce:**

```
use polars::prelude::*;

#[macro_use]
extern crate polars;

fn main() {
    let ca = Int32Chunked::new_from_slice("foo", &[1, 2, 3, 2, 1]);
    let a  = ca.rolling_min(3, None, true).unwrap();
    print!("{:?}", a);
}
```
Output:
```
ChunkedArray: '' [Int32]
[
        1
        1
        1
        2
        1
]
```
**Expected Results**

I expect the following output:
```
ChunkedArray: '' [Int32]
[
        None
        None
        1
        2
        1
]
```

The reason why the first 2 values should be None is because this particular rolling window requires 3 values in order to be able to calculate a result - that is why it should return Some() value only after reaching the 3rd element of the input `ChunkedArray<Int32Type>`. Put it another way, it needs to "accumulate" 3 values before being able to calculate the result for a given window.

As a sanity check, I did the same with pandas:

```
import pandas as pd

s = pd.Series([1, 2, 3, 2, 1])
print(s)

m = s.rolling(3).min()
print(m)
```

Output:

```
0    1
1    2
2    3
3    2
4    1
dtype: int64
0    NaN
1    NaN
2    1.0
3    2.0
4    1.0
dtype: float64
```

**Comment by ritchie46** [comment]
Well.. This is as expected. At the moment it is implemented with 'boundary effects' similar to what described in [numpy.convolve](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html). We could add an `enum` argument to define the boundary effects.

**Comment by rubyfin** [comment]
> Well.. This is as expected. At the moment it is implemented with 'boundary effects' similar to what described in [numpy.convolve](https://numpy.org/doc/stable/reference/generated/numpy.convolve.html). We could add an `enum` argument to define the boundary effects.

I think it would provide a lot more flexibility and allow more people to use the library if the user could control the calculation method here. For example, calculating a rolling n-days SMA (simple moving average) in finance will compute a rolling unweighted mean of the previous n points, and for the first n-1 points SMA would be None.

**Comment by alippai** [comment]
It'd be similar to `min_periods` in Pandas, right? https://pandas.pydata.org/docs/reference/api/pandas.Series.rolling.html#pandas.Series.rolling

**Comment by rubyfin** [comment]
> It'd be similar to `min_periods` in Pandas, right? https://pandas.pydata.org/docs/reference/api/pandas.Series.rolling.html#pandas.Series.rolling

Right, panda's equivalent of the way polars is currently working would be passing in `min_periods=1` in pandas, e.g. `s.rolling(3 min_periods=1).min().`

Looking at the source code at https://github.com/pandas-dev/pandas/blob/master/pandas/core/window/rolling.py, it defaults to the size of the window for this param, if not provided:

```
  window_indexer = self._get_window_indexer()
        min_periods = (
            self.min_periods
            if self.min_periods is not None
            else window_indexer.window_size
        )
```

I think ritchie46 mentioned a slightly different approach by defining an enum of mode of calculation to define boundary effects. Depending on implementation, it might provide a way to achieve the same output as pandas.

**Comment by ritchie46** [comment]
FYI, will go for the same API as pandas for this one, as that seems most flexible.

**Comment by rubyfin** [comment]
> FYI, will go for the same API as pandas for this one, as that seems most flexible.

You decided to introduce `min_periods` as well? It does provide more flexibility for sure. Quite often you want to control how many valid values you must have in a window to return a result from applying a certain function on the window.

Pandas API for Rolling is pretty powerful, it supports a ton of SciPy window functions: https://docs.scipy.org/doc/scipy/reference/signal.windows.html#module-scipy.signal.windows.
