### ISSUE TITLE
Implement dataframe apply

### ISSUE THREAD

**Issue by impredicative** [ritchie46/polars#401]
I really need to do a dataframe apply. I consider this to be a fundamental operation. Moving to Pandas and back for this operation would too inefficient.

An alternative which I considered is a dataframe groupby, but it caused SIGKILL or SIGBUS when used over the entire dataframe.It worked correctly for a small sample of the data. I don't want to use groupby.

As for iterating over the rows, I don't see of a way to do it either. Even if it were possible, it would be inefficient relative to the dataframe apply.

**Comment by ritchie46** [comment]
Help me understand your problem a bit more? At the moment you can apply over the columns of a DataFrame, do you want to apply over whole rows? Can you show an MWE?

**Comment by impredicative** [comment]
I need to create a virtual new ID column by hashing unique rows of specific columns of a dataframe. Here is an example:

```python
from base64 import urlsafe_b64encode
from hashlib import shake_128

import pandas as pd
import pypolars as pl
import smart_open


def series_to_str_id(pd_series: pd.Series) -> str:
    return urlsafe_b64encode(shake_128(str(tuple(pd_series)).encode()).digest(16)).decode()

def catstr_to_idstr(in_str: str) -> str:
    return series_to_str_id((in_str,))

# Read dataframe
df = pl.read_csv(smart_open.open('https://j.mp/iriscsv', 'rb')).drop_duplicates()
original_columns = df.columns.copy()

# Create row hash ID column using pandas df.apply
# NOTE: For this, conversion to pandas and back is inefficient.
df['pd_row_hash_id'] = df.to_pandas().apply(series_to_str_id, axis="columns")

# Create row hash ID column using pypolars series.apply
# NOTE: For this, creating and storing a concatenated str column is inefficient.
tmp_pl_row_hash_id_members: pl.Series = sum([member for column in original_columns for member in (df[column], ';') ])
df['pl_row_hash_id'] = tmp_pl_row_hash_id_members.apply(catstr_to_idstr)
del tmp_pl_row_hash_id_members
```

As shown above, I currently have two workarounds, both of which are inefficient in different ways.

**Comment by impredicative** [comment]
To summarize, `df.apply` will help me from an efficiency point-of-view, and I certainly look forward to using in the future if possible. I'm processing healthcare data where the construction of such IDs as in the example above is vital.

**Comment by ritchie46** [comment]
Just to make it clear, you'd expect a DataFrame row as a python tuple when you iterate the DataFrame?

**Comment by impredicative** [comment]
> you'd expect a DataFrame row as a python tuple when you iterate the DataFrame?

Personally I would indeed, but any pypolars structure that can get me to a tuple is fine. For example, if I can convert a single-row pypolars dataframe or a pypolars series to a tuple, then the respective pypolars data structure will be fine. In summary, I think **a single-row dataframe would be most intuitive and general, but only if it is somehow convertible to a tuple**.

**Comment by ritchie46** [comment]
Going from Polars to tuple rows would still be very slow. A faster approach would be utilizing the new fold function in  #446

Until that is released you could do that like this:

```python
    def fold(
        df: DataFrame, operation: "Callable[['Series', 'Series'], 'Series']"
    ) -> "DataFrame":
        """
        Apply a horizontal reduction on a DataFrame. This can be used to effectively
        determine aggregations on a row level, and can be applied to any DataType that
        can be supercasted (casted to a similar parent type).

        An example of the supercast rules when applying an arithmetic operation on two DataTypes are for instance:

        Int8 + Utf8 = Utf8
        Float32 + Int64 = Float32
        Float32 + Float64 = Float64

        # Examples

        ## A horizontal sum operation
        ```python
        >>> df = pl.DataFrame(
            {"a": [2, 1, 3],
            "b": [1, 2, 3],
            "c": [1.0, 2.0, 3.0]
        })

        >>> fold(df, lambda s1, s2: s1 + s2)
        ```
        ```text
        Series: 'a' [f64]
        [
            4
            5
            9
        ]
        ```

        ## A horizontal minimum operation

        ```python
        >>> df = pl.DataFrame(
            {"a": [2, 1, 3],
            "b": [1, 2, 3],
            "c": [1.0, 2.0, 3.0]
        })

        >>> fold(df, lambda s1, s2: s1.zip_with(s1 < s2, s2))
        ```
        ```text
        Series: 'a' [f64]
        [
            1
            1
            3
        ]
        ```

        ## A horizontal string concattenation
        ```python
        >>> df = pl.DataFrame(
            {"a": ["foo", "bar", 2],
            "b": [1, 2, 3],
            "c": [1.0, 2.0, 3.0]
        })

        >>> fold(df, lambda s1, s2: s1 + s2)
        ```
        ```text
        Series: '' [f64]
        [
            "foo11"
            "bar22
            "233"
        ]
        ```

        Parameters
        ----------
        operation
            function that takes two `Series` and returns a `Series`
        """
        if self.width == 1:
            return self
        df = self
        acc = operation(df[0], df[1])

        for i in range(2, df.width):
            acc = operation(acc, df[i])
        return acc

```

The last example in the docstring shows how you get a Utf8 Series and then you can use apply to determine the hash.

**Comment by impredicative** [comment]
`fold` doesn't really make any sense to me. It doesn't get me a tuple in any way that I know how.

Ideally, I don't really want a series of concatenated strings, as holding this in memory would be pointlessly memory inefficient.

I don't understand why the issue was closed. Even [`vaex`](https://vaex.io/docs/api.html) has a dataframe apply method, providing how it is a commonly expected method.

**Comment by ritchie46** [comment]
Using fold to get a Series is the fastest way to do what you want to do (due to columnar access). You can then use that Series to do an apply and compute the hash you want. 

If you think thats too memory efficient, you can use a loop and `df.get_tuple(idx)`, But this will likely be a lot slower.

**Comment by impredicative** [comment]
> you can use a loop and df.get_tuple(idx)

This is no helping me at all. There is no `df.get_tuple`.

We're having a pointless discussion when the obvious solution of a parallel `df.apply` over row tuples, if it were to exist, would work optimally. Other dataframe packages have it for a reason.

**Comment by ritchie46** [comment]
I meant [df.row](https://github.com/ritchie46/polars/blob/35f789aa26ecad3e5ffc64903425690dc6796279/py-polars/polars/frame.py#L1463).

> We're having a pointless discussion when the obvious solution of a parallel df.apply over row tuples, if it were to exist, would work optimally. Other dataframe packages have this method for a reason.

It's not so obvious. A parallel apply doesn't make sense as only a [single thread may access a python object](https://wiki.python.org/moin/GlobalInterpreterLock), so parallelism in Python would not give you any speed up at all. 

Anyhow. I am just trying to help. If a DataFrame apply was easy to implement, and if I already made up what the return type of an apply would be, and if it gave you something you couldn't do right now, I would have released it today.

Here is an example that may help your case:

```python
from base64 import urlsafe_b64encode
from hashlib import shake_128

df = pl.read_csv('https://j.mp/iriscsv').drop_duplicates()
print(df.fold(lambda a, b: a + b).apply(lambda s: urlsafe_b64encode(shake_128(s.encode()).digest(16)).decode()))
```

You'll obtain a hash per DataFrame row, which I am under the impression is the thing you want to acquire.

```text
Series: '' [str]
[
	"lYpVi-n4Dh..."
	"F2pP9LTegx..."
	"r6WASLdIUY..."
	"Rpw4cbpSj2..."
	"lYpVi-n4Dh..."
	"U8QTO8rhd3..."
	"YU9lTmS1HR..."
	"PwBl1qBCwg..."
	"evTj21Gipl..."
	"S3hpHWfjvB..."
]

```

**Comment by impredicative** [comment]
My issue with `df.fold(lambda a, b: a + b)` is that my dataframe has nearly 50 columns and 1.3 billion rows. Attempting to concatenate it as a temporary unique string series would almost certainly exceed the available memory, and this is avoidable in theory. In contrast, the end result (hash string series) itself doesn't use too much memory.

**Comment by ritchie46** [comment]
If you are in tight memory you could do the operation in chunks, where you use a chunk size that is acceptable for your use case.

```python
def myhash(s: str) -> str:
    return urlsafe_b64encode(shake_128(s.encode()).digest(16)).decode()
    

n_chunks = 10
chunk_size = int(df.height / n_chunks)
out = None

for i in range(n_chunks):
    start = i * chunk_size
    end = start + chunk_size
    
    h = df[start:end].fold(lambda a, b: a + b).apply(myhash)
        
    if out is None:
        out = h
    else:
        out.append(h)
    

# remaining rows
out.append(df[end:].fold(lambda a, b: a + b).apply(myhash))

assert len(out) == df.height
```

**Comment by impredicative** [comment]
> you could do the operation in chunks

Thank you for the sample code. Although this would work, if `df.apply` were to exist, as a user I could then altogether avoid having to explicitly chunk.
