### ISSUE TITLE
The compile time is more than 6 minutes on linux.

### ISSUE THREAD

**Issue by CHCP** [ritchie46/polars#402]
Hi @ritchie46 ,
 I use Polars in my project, when I compile source code on linux, it takes more than 6 minutes, a bit long time for waiting.  But if I remove Polars from the project, it only takes 1 minute. 

Is there any special settings to reduce the compile time? Thanks.

rust toolchain: nightly-x86_64-unknown-linux-gnu
rust target: x86_64-unknown-linux-gnu

![polars-compile](https://user-images.githubusercontent.com/5645296/110399668-4f78d480-80ca-11eb-86e8-1441060716a3.png)

**Comment by CHCP** [comment]
The similar question:
  When I compile code with Polars, the executable file size is almost 20M, but it is only 6M without Polars,  20M is too big for me. So if I only use the DataFrame and CVS modules , how to define the Polars features in Cargo.toml?  Thanks

**Comment by ritchie46** [comment]
The compile time are not great, I agree. However, there are no easy wins here. If you only use the eager API, you can use:

```
features = [
    "temporal",
    "performant",
    "plain_fmt"
]
```

About the size of the binary, didn't you say you used pandas before this? :wink:

**Comment by CHCP** [comment]
1、I use features in Cargo.toml like this:

```
polars = { version = "0.12.1", features = ["temporal", "performant", "plain_fmt"] }
```

but there are some errors:
```
the package `ohlc` depends on `polars`, with features: `performant` but `polars` does not have these features.
```
so I only use the "default" feature.

2、Yes, I used to use Pandas in my project, but it is hard to call with Pyo3, and the low performance. I had remove Pyo3 from project, so it didn't effect the binary file size.

Any way, "compile time" and "binary file size" are two small issues, just for the best optimization.

**Comment by ritchie46** [comment]
Oh, sorry, I assumed you were on master. The features for the latest release are shown here: https://docs.rs/crate/polars/0.12.1/features

Turning off `lazy` will reduce quite some code compilation. I am refactoring lazy to reduce some code bloat, but that will take a while to land.

P.S. don't forget to set `default_features=false`.

**Comment by CHCP** [comment]
Thanks @ritchie46 , I will try this.

**Comment by ritchie46** [comment]
Hi @CHCP check #423. This will greatly reduce compile times. I will add more data-types coming week, so compile times and binary size will continue to increase. You only need to decide up front which data types you want to work for your binray.

**Comment by CHCP** [comment]
Hi @ritchie46 
  Great job. I am waiting for the new crates release, it still is 0.12.1 now.
