### ISSUE TITLE
Panic: No root column name could be found for expr SHIFT data by 1 in output name utillity

### ISSUE THREAD

**Issue by TheDan64** [ritchie46/polars#406]
```rust
let data = vec![1., 2., 3.];
let df = DataFrame::new(vec![
    Series::new("data", data),
])?;
df.lazy().with_column(col("data").shift(1).fill_none(lit(0.0)).alias("output")).collect()?;
```

Panics with: `Other("No root column name could be found for expr SHIFT data by 1 in output name utillity")`

**Comment by TheDan64** [comment]
Similar problem maybe:

```rust
let data = vec![true, false, true];
let df = DataFrame::new(vec![
    Series::new("data", data),
])?;
df.lazy().with_column(col("data").and(col("data")).fill_none(lit(true)).alias("output")).collect()?;
```

Panics with: `Other("could not determine output name between two root columns")`

**Comment by ritchie46** [comment]
For the second one, this is expected behavior. A binary expression in a `projection` is not allowed. There could be a better panic information though.

I will take a look at the first query.
