### ISSUE TITLE
thread 'main' panicked at 'path should be set' - error

### ISSUE THREAD

**Issue by russellb23** [ritchie46/polars#408]
All I am trying to do is, read a csv and print to view it.

I am getting the following error:

> thread 'main' panicked at 'path should be set', /home/russellb/.cargo/registry/src/github.com-1ecc6299db9ec823/polars-io-0.12.1/src/csv_core/csv.rs:378:43

My code is as follows,
```

use polars::prelude::*;
use polars_core::prelude::*;

use std::fs::File;

fn get_data() -> Result<DataFrame> {
    let file = File::open("/home/russellb/Development/rs_devel/play/warmup/csvtutorial/aap.csv")
        .expect("could not read file");

    let mm = CsvReader::new(file).infer_schema(None).has_header(true).finish();
    let pp = mm.unwrap().clone();
    println!("{:?}", pp);
    Ok(pp)
}

fn main() {
    println!("Polar Data-Frames (In-memory)");

    let df = get_data().unwrap().head(Some(10));
    println!("{:?}", df);

```

**Comment by ritchie46** [comment]
Hi, Could you try: https://ritchie46.github.io/polars/polars/prelude/struct.CsvReader.html#method.from_path

**Comment by russellb23** [comment]
That worked. Thanks mate.
