### ISSUE TITLE
Parsing date

### ISSUE THREAD

**Issue by russellb23** [ritchie46/polars#412]
What is the current best way to parse dates. 

[This](https://docs.rs/polars/0.12.1/polars/doc/time/index.html) talks about string slice. What I am looking for is something close to pandas `parse_date` argument when reading csv. 

I could not find any such option in CsvReader. I appreciate any help.

**Comment by ritchie46** [comment]
At the moment this is still a two-phase process. 

1. first read in csv.
2. parse string column as date.

There is an example in this [issue](https://github.com/ritchie46/polars/issues/381#issuecomment-791959754)

**Comment by russellb23** [comment]
Thanks mate!
