### ISSUE TITLE
Lazy DataFrame slice from tail

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#417]
Let `slice` accept an i64, and when it's negative use it as a tail operation. Also implement tail and last for LazyFrame.

**Comment by ErikDeSmedt** [comment]
I just had a look at the source-code and decided I would like to do an attempt at solving this one. 

I propose to make the changes in both the eager and the lazy API. If we make the change in the eager API we would only need to change the type from `usize` to `i64` in the lazy API.

This would keep both API's consistent. However, it would introduce a breaking change in both the eager and lazy API.

Do you think that is the right approach?

**Comment by ritchie46** [comment]
That seems good to me. +1

**Comment by ErikDeSmedt** [comment]
I tried to provide an implementation for which I sent a pull-request.
The windows CI-job fails to compile due to an out-of-memory error.
Is this an issue you have seen before? Do you have any idea how to tackle that issue?

**Comment by ritchie46** [comment]
Yes, the Windows linker OOMs due to the many datatypes we compile in the Series objects. This is ok, and happens all the time, so no worries. :)
