### ISSUE TITLE
Reading CSV is slower in multithreading.

### ISSUE THREAD

**Issue by haixuanTao** [ritchie46/polars#419]
# Summary 

In one of my test, this:
```rust
    let mut df = CsvReader::from_path(path)?
        .with_encoding(CsvEncoding::LossyUtf8)
        .with_n_threads(Some(1))
        .has_header(true)
        .finish()?;
```
was faster than, this:
```rust
    let mut df = CsvReader::from_path(path)?
        .with_encoding(CsvEncoding::LossyUtf8)
        .has_header(true)
        .finish()?;
```
# To reproduce

The csv, I used is the following: https://www.kaggle.com/c/predict-closed-questions-on-stack-overflow/data?select=train_October_9_2012.csv

I haven't digged on the reason of the time increase

**Comment by ritchie46** [comment]
Thanks for the PR. Could you tell me on which OS you are working. And what do you retrieve when you request the number of CPU's with https://docs.rs/num_cpus/1.13.0/num_cpus/?

**Comment by haixuanTao** [comment]
Running this gives me 12 cpus.

I can't upload svg directly to github so you'll find them as zip.
[flamegraphs.zip](https://github.com/ritchie46/polars/files/6135098/flamegraphs.zip)

My setup is:
Ubuntu 20.04.2 LTS
64-bit
Intel® Core™ i7-8750H CPU @ 2.20GHz × 12

**Comment by ritchie46** [comment]
Thanks for your effort. I hope to look into it next week.
