### ISSUE TITLE
Naming of Python bindings: pypolars vs polars

### ISSUE THREAD

**Issue by nickray** [ritchie46/polars#428]
Hi

This is such an exciting project :) It simultaneously tackles all of the things that have bugged me about Pandas for ages.

I wanted to ask if importing it as `pypolars` on the Python side was a conscious choice. Understood from Rust side it's helpful to distinguish (and could still be done), but from a purely Python user side, it seems it would be less crufty to just `import polars` and start cracking. This is a bit of a pet peeve (as when I'm in Python world I already know that without being reminded constantly), so count this is a single opinion.

In my understanding, it's a relatively minor change to rename polars/py-polars/pypolars directory to ../polars, modify the [lib] name in py-polars/Cargo.toml, [pymodule] name, etc. etc., but before I prepare a PR I wanted to ask.

**Comment by ritchie46** [comment]
Hi Nick, 

Thanks for your support! :) I hope that we can make it a serious contender to Pandas.

This has been discussed earlier. To be honest I also don't like the sound of `py-polars`. I just made that decision once without thinking too much of it. 

But now that it's getting traction, it's maybe wise to do renaming as early as possible. If you can make it work and update the docs, I will accept that PR.

Note to self: if this get merged do a PR with the name change in https://github.com/h2oai/db-benchmark

**Comment by rosykat** [comment]
Hi
