### ISSUE TITLE
Projection pushdown failure

### ISSUE THREAD

**Issue by nickray** [ritchie46/polars#439]
I managed to come up with the following join of lazy dataframes that fails with `RuntimeError: Any(NotFound("link_karma"))`.
Weird file extensions because GitHub.

[bad-join.py.txt](https://github.com/ritchie46/polars/files/6142597/bad-join.py.txt)
[reddit10k.csv.txt](https://github.com/ritchie46/polars/files/6142598/reddit10k.csv.txt)

Predicate pushdown and expression simplification seem to be working, it's just the projection pushdown.

For context: The goal of the example was to see if I could define the "metrics" on the two karma types independently, then join or stack the results, then have the query optimizer find out it can do both in a single operation. This would be useful for a "backend" that calculates metrics on a given granularity, coming in over an API.

**Comment by ritchie46** [comment]
I will just expand the file for clarity.

```python
import polars as pl
from polars import col

reddit = pl.scan_csv("reddit10k.csv.txt")

comment_by_name = (reddit
    .select([col("name").apply(lambda s: s[:1]), col("comment_karma").alias("comment")])
    .groupby("name")
    .agg([
        col("comment").n_unique().alias("unique_comment"),
        col("comment").sum()
    ])
)

link_by_name = (reddit
    .select([col("name").apply(lambda s: s[:1]), col("link_karma").alias("link")])
    .groupby("name")
    .agg([
        col("link").n_unique().alias("unique_link"),
        col("link").sum()
    ])
)

joined = comment_by_name.fetch(10).join(link_by_name.fetch(10), on="name")

print(comment_by_name.join(link_by_name, on="name").collect(predicate_pushdown=True, projection_pushdown=False, simplify_expression=True))
comment_by_name.join(link_by_name, on="name").collect(predicate_pushdown=True, projection_pushdown=True, simplify_expression=True)
```

**Comment by nickray** [comment]
Thanks, yeah I guess it's short enough. The reddit10k data set is just a small random sample of the data set from the book. The penultimate line works, the final line fails.

**Comment by ritchie46** [comment]
It seems there is an accidental fix. With latest `polars==0.7.0_beta.1` I can run the query.

**Comment by nickray** [comment]
I presume the intention would still be to have this optimize to

![both dot](https://user-images.githubusercontent.com/1092423/111470914-a153d700-8728-11eb-9099-7085f62fa942.png)

instead of

![optimized dot](https://user-images.githubusercontent.com/1092423/111470936-a7e24e80-8728-11eb-9526-8540f89f88cc.png)

though, right? The query optimizer simply is in a state of WIP?

**Comment by ritchie46** [comment]
Yes, indeed. I assume that an optimizer will always be in sort of WIP state. This is an interesting query indeed. I think we need another query pass to accumulate all aggregations of a table.
