### ISSUE TITLE
groupby aggregate functions

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#44]
Can also implement median for ChunkedArray

**Comment by YuRiTan** [comment]
Such as:
- `.mean()`
- `.median()`
- `.first()`
- `.last()`
- `.nunique()`

**Comment by ritchie46** [comment]
Status:

- [x] mean
- [ ] median
- [x] first
- [ ] last
- [x] min
- [x] max
- [x] sum
- [ ] nunique

**Comment by koaning** [comment]
I just took this for a spin. I wondered. The there a reason for the `.select().sum()` syntax as opposed to the `.agg()` in pandas?

**Comment by ritchie46** [comment]
> I just took this for a spin. I wondered. The there a reason for the `.select().sum()` syntax as opposed to the `.agg()` in pandas?

No specific reason. The python api closely resembles the Rust api and isn't per se meant to be a copy of Pandas (however familiarity is beneficial). 

We could default to all selected columns by default and only aggregate the columns that are summable. That would be a more ergonomic default. `groupby("foo").sum()`

**Comment by koaning** [comment]
In pandas right now I can do; 

```python
df.groupby('user_id').agg(n_sess=('session', 'nunique'), avg_session_len=('session_time', 'mean'))
```

After grouping I can calculate multiple aggregations and I can be specific. I can specfiy here that I want the number of unique sessions and the average session time. How might that work here?

**Comment by ritchie46** [comment]
Right! We cannot yet. :smile: This was already [requested in #75 ](https://github.com/ritchie46/polars/issues/75). It's coming. I think that we can also support the same syntax on the Python side
