### ISSUE TITLE
How to get the correct date with SampleRule::Day(n)

### ISSUE THREAD

**Issue by CHCP** [ritchie46/polars#474]
Hi @ritchie46 
  In my case, I use SampleRule::Day() to get the DataFrame date, but I can't get the correct date. 

my csv file data:
```
TESTSYMBOL,20210319 23:58:49.724418,0.9145,0.95476,1
TESTSYMBOL,20210319 23:58:49.780350,0.9545,0.95476,1
TESTSYMBOL,20210319 23:58:49.826159,0.9545,0.95476,1
TESTSYMBOL,20210319 23:58:49.860344,0.95449,0.95476,1
TESTSYMBOL,20210319 23:58:50.163641,0.95449,0.9547,1
TESTSYMBOL,20210319 23:58:50.186391,0.95447,0.95469,10
TESTSYMBOL,20210319 23:58:50.238856,0.95449,0.95472,1
TESTSYMBOL,20210319 23:58:50.290935,0.95443,0.95467,1
TESTSYMBOL,20210319 23:58:50.341803,0.95443,0.95467,1
```

my test code:
```
     rule = SampleRule::Day(1);
    let df_ohlc = df.downsample("u", rule).unwrap()
        .agg(&[("c", &["first", "max", "min", "last"])]).unwrap()
        .sort("u", false).unwrap();
    debug!("Symbol = {}, period type = {}, ohlc === {:?}", value.s, value.t, df_ohlc);
```

the test result:
```
 rule = SampleRule::Day(1)  -->  2021-03-19 00:00:00   //correct
 rule = SampleRule::Day(2)  -->  2021-03-18 00:00:00   //correct
 rule = SampleRule::Day(3)  -->  2021-03-19 00:00:00   //not correct, should be 2021-03-17 00:00:00
 rule = SampleRule::Day(4)  -->  2021-03-18 00:00:00   //not correct, should be 2021-03-16 00:00:00
 rule = SampleRule::Day(5)  -->  2021-03-19 00:00:00   //not correct, should be 2021-03-15 00:00:00
 rule = SampleRule::Day(6)  -->  2021-03-16 00:00:00   //not correct, should be 2021-03-14 00:00:00
 rule = SampleRule::Day(7)  -->  2021-03-18 00:00:00   //not correct, should be 2021-03-13 00:00:00
```

Only SampleRule::Day(1) and SampleRule::Day(2)  are correct, all others are errors. So how to use the SampleRule::Day() in a correct way?  Thank you very much?

**Comment by ritchie46** [comment]
I will take a look!

**Comment by ritchie46** [comment]
Ok, I don't think I understand your question. The sample rule discretetizes the date column by doing a floor divide and then aggregating the values that match that bucket. The `n` parameter in date represent the step size per bucket. But all the buckets could start at the same point.

**Comment by CHCP** [comment]
Hi ritchie46,
  Sorry for these test records, they are misleading.

  I use Polars to calculate OHLC(first/hight/low/last) for some stocks, there are ten period to calculate such as: 1 minute, 5 minutes, 15 minutes, 30 minutes, 1 hour, 2 hours, 4 hours, 1 day, 1 week, 1 month.

  I have got the correct results for less than 1 day periods, only "1 week" and "1 month" I didn't get the correct results yet.

  The "1 week" period need to calculate from Monday to Sunday's records of one whole week, and the "1 month" period need to calculate from the first day to the last day's records of one whole month.

  There are some updated records, and the wanted period results:
```
AUDCAD,20210310 23:58:58.274130,0.95436,0.9546,1
AUDCAD,20210310 23:58:58.698742,0.95436,0.9546,1
AUDCAD,20210311 23:58:57.175739,0.95447,0.95467,1
AUDCAD,20210311 23:58:57.734865,0.95447,0.95465,1
AUDCAD,20210312 23:58:55.452786,0.95448,0.95467,1
AUDCAD,20210312 23:58:55.504465,0.95447,0.95467,1
AUDCAD,20210313 23:58:55.010101,0.95452,0.95468,1
AUDCAD,20210313 23:58:55.117064,0.95452,0.95473,1
AUDCAD,20210314 23:58:54.795659,0.95452,0.95472,1
AUDCAD,20210314 23:58:54.808425,0.95452,0.95472,1
AUDCAD,20210315 23:58:54.510919,0.95446,0.95468,1
AUDCAD,20210315 23:58:54.565217,0.95449,0.95468,2
AUDCAD,20210316 23:58:50.597161,0.95443,0.95467,1
AUDCAD,20210316 23:58:50.650509,0.95443,0.95467,1
AUDCAD,20210317 23:58:50.186391,0.95447,0.95469,1
AUDCAD,20210317 23:58:50.238856,0.95449,0.95472,1
AUDCAD,20210317 23:58:50.290935,0.95443,0.95467,1
AUDCAD,20210318 23:58:49.724418,0.9145,0.95476,1
AUDCAD,20210318 23:58:49.780350,0.9545,0.95476,1
AUDCAD,20210319 23:59:01.204388,0.95436,0.9546,1
AUDCAD,20210319 23:59:02.724714,0.95436,0.9546,1
```

 The wanted period results are two records, ignore OHLC values:
```
 u       ┆ c_first ┆ c_max ┆ c_min ┆ c_last
2021-03-08 00:00:00  0.95 0.96 0.91 0.92
2021-03-15 00:00:00  0.95 0.96 0.91 0.92
```
Period "2021-03-08" calculate records from 2021-03-08 00:00:00(Monday) to 2021-03-14 23:59:59.999999(Sunday), and period "2021-03-15" calculate records from 2021-03-15 00:00:00(Monday) to 2021-03-21 23:59:59.999999(Sunday).

I wondering if Polars can implement those "1 week" and 1 "month" period results, if YES, how would I to do?  if NOT, would you like to implement these features? 

Thank you very much.

**Comment by ritchie46** [comment]
Hmm.. At the moment it isn't supported directly. As in `SampleRule::Day(7)` gives you no guarantee of the start of the bucket. I could at this as a feature, but this isn't a high priority at the moment. Perhaps you could experiment a bit and report in this issue? That would speed up things.

You can always use all the `chrono` functionallity. Polars already implemented a lot for you, so you could for instance already get the `month` values and `groupby` month. Currently the week requires `chrono`, but I could easily add that.

**Comment by ritchie46** [comment]
FYI, I added `week` and `weekday` impls to `Series`

**Comment by CHCP** [comment]
Hi ritchie46,
  Thank you very much.
  I will try to implement the "month" feature, then report this PR. But it will take a few days because I am not familiar with Polars.

  Have a good weekend.

**Comment by CHCP** [comment]
Would you like to give a tag on the latest master branch? 

Or update Polars from 0.12.1 to a new version in cates.io?   Thanks a lot.

**Comment by ritchie46** [comment]
You could use commit hash like I do with arrow for instance:

https://github.com/ritchie46/polars/blob/e2ffbea2d22a5a3ca627a48fda7e82ce57db7e2d/polars/polars-core/Cargo.toml#L43

I cannot update to crates.io untill a new version of arrow is released.

**Comment by CHCP** [comment]
Hi ritchie46,
     There are two questions when I got the latest tag code to compile,
Q1: 
```
Cargo.toml:
polars = {git = "https://github.com/ritchie46/polars", tag = "py-polars-v0.7.3"} 
```

and there is an error that I nerver seen, how to fix it?
```
error[E0277]: the trait bound `ChunkedArray<Date64Type>: IntoSeries` is not satisfied
  --> src\base_ohlc\polars_ohlc.rs:56:28
   |
56 |                         df.may_apply("u", |s| s.utf8().unwrap().as_date64(cast_fmt)).unwrap();
   |                            ^^^^^^^^^ the trait `IntoSeries` is not implemented for `ChunkedArray<Date64Type>`
   |
   = help: the following implementations were found:
             <ChunkedArray<BooleanType> as IntoSeries>
             <ChunkedArray<CategoricalType> as IntoSeries>
             <ChunkedArray<Float32Type> as IntoSeries>
             <ChunkedArray<Float64Type> as IntoSeries>
           and 5 others
```

Q2:
  I read the week/weekday source code carefully, but I don't known how to use them, because there is no Week function in SampleRule such as SampleRule::Week(1).   So need I to complete the SampleRule::Week(1) functions?
```
  rule = SampleRule::Week(1);
  let df_ohlc = df.downsample("u", rule).unwrap()
        .agg(&[("c", &["first", "max", "min", "last"])]).unwrap()
        .sort("u", false).unwrap();
```

Thanks a lot.

**Comment by ritchie46** [comment]
> and there is an error that I nerver seen, how to fix it?

Yes, Series compile paths are now opt-in. This drastically reduces compile times. [See](https://ritchie46.github.io/polars/polars/index.html#compile-times-and-opt-in-data-types)

> I read the week/weekday source code carefully, but I don't known how to use them, because there is no Week function in SampleRule such as SampleRule::Week(1). So need I to complete the SampleRule::Week(1) functions?

You can create unqiue identifiers by combining a week and year and then groupby.

Something like this in pseudocode/python

```python

# create a unique str id like:
# "202102"
# "202103"
df["unique"] = df["date"].year().cast(str) + df["date"].week()

df.groupby("unique").agg([first, max, min, last])
```

**Comment by CHCP** [comment]
Thanks, @ritchie46

**Comment by ritchie46** [comment]
@CHCP Come to think of it, you don't have to create a string column `unique`, which is needlessly expensive. You can also create a column `year` and `week` and group on both of them.

**Comment by ritchie46** [comment]
I will take a look, if I can redesign the downsample functionality a bit.

**Comment by CHCP** [comment]
Ｉ will try this new API, thanks ritchie46.

**Comment by CHCP** [comment]
Hi @ritchie46 
 I use the new source code of tag "py-polars-0.7.4", I found some issues:
1、the date is different from the older tag "py-polars-0.7.3",  tag 0.7.3 are as same as python "Pandas",  that is correct. 

py-polars-0.7.3(SampleRule::Minute(15)):
```
 u                   ┆ c_first ┆ c_max ┆ c_min ┆ c_last │
│ ---                 ┆ ---     ┆ ---   ┆ ---   ┆ ---    │
│ date64(ms)          ┆ f32     ┆ f32   ┆ f32   ┆ f32    │
 | 2021-03-18 23:45:00 ┆ 0.914   ┆ 0.955 ┆ 0.914 ┆ 0.954  │
│ 2021-03-19 23:45:00 ┆ 0.954   ┆ 0.974 ┆ 0.952 ┆ 0.952  │
```

py-polars-0.7.4(SampleRule::Minute(15)): 
```
 u                   ┆ c_first ┆ c_max ┆ c_min ┆ c_last │
│ ---                 ┆ ---     ┆ ---   ┆ ---   ┆ ---    │
│ date64(ms)          ┆ f32     ┆ f32   ┆ f32   ┆ f32    │
 | 2021-03-18 23:57:49.724 ┆ 0.914   ┆ 0.955 ┆ 0.914 ┆ 0.954  │
│ 2021-03-19 23:59:01.204 ┆ 0.954   ┆ 0.974 ┆ 0.952 ┆ 0.952  │
```
the date "u" should be "2021-03-18 23:45:00", "2021-03-19 23:45:00", and all other periods are different from tag 0.7.3.

2、when I use Week(1), there are some errors:
```
    let df_ohlc = df.downsample("u", SampleRule::Week(1)).unwrap()
        .agg(&[("c", &["first", "max", "min", "last"])]).unwrap()
        .sort("u", false).unwrap();
```

errors:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NotFound("__POLARS_TEMP_WEEK")'
```
But where define "__POLARS_TEMP_WEEK"?

Thanks

**Comment by ritchie46** [comment]
Hmm, that's my bad. I believe it should be fixed now.

**Comment by CHCP** [comment]
Hi @ritchie46 
  All date64 changed to "1970-01-01",  I think there are something wrong.

```
╭─────────────────────────┬─────────┬───────┬───────┬────────╮
│ u                       ┆ c_first ┆ c_max ┆ c_min ┆ c_last │
│ ---                     ┆ ---     ┆ ---   ┆ ---   ┆ ---    │
│ date64(ms)              ┆ f32     ┆ f32   ┆ f32   ┆ f32    │
╞═════════════════════════╪═════════╪═══════╪═══════╪════════╡
│ 1970-01-01 00:03:44.499 ┆ 0.952   ┆ 0.952 ┆ 0.952 ┆ 0.952  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1970-01-01 00:03:44.501 ┆ 0.952   ┆ 0.952 ┆ 0.952 ┆ 0.952  │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌┤
│ 1970-01-01 00:03:44.502 ┆ 0.952   ┆ 0.962 ┆ 0.912 ┆ 0.962  │
╰─────────────────────────┴─────────┴───────┴───────┴────────╯
```

**Comment by ritchie46** [comment]
Sorry about that. That's fixed now. Only thing is, that the start of each bucket may not be as you expect. What is a start of a week for instance? The week numbers don't coincide with the start of a month.

**Comment by CHCP** [comment]
Yes, the Week calculation is the most difficult than all others period.

In Python Pandas, The Week period is from Monday to Sunday, seven days in total; the Month period is from the first day to last day of this month.

If the date of one record is within week A, then the start of Week is the Monday of week A, for example:
```
AUDCAD,20210221 23:58:58.274130,0.95436,0.9546,1
AUDCAD,20210222 23:58:58.698742,0.95436,0.9546,1
AUDCAD,20210223 23:58:57.175739,0.95447,0.95467,1

AUDCAD,20210311 23:58:57.734865,0.95447,0.95465,1
AUDCAD,20210312 23:58:55.452786,0.95448,0.95467,1
AUDCAD,20210313 23:58:55.117064,0.95452,0.95473,1
AUDCAD,20210314 23:58:54.795659,0.95452,0.95472,1
AUDCAD,20210315 23:58:54.565217,0.95449,0.95468,2
AUDCAD,20210316 23:58:50.650509,0.95443,0.95467,1
AUDCAD,20210317 23:58:50.186391,0.95447,0.95469,1
AUDCAD,20210318 23:58:49.780350,0.9545,0.95476,1
AUDCAD,20210319 23:59:02.724714,0.95436,0.9546,1
```

the expected results for Week calculation are:
```
 u       ┆ c_first ┆ c_max ┆ c_min ┆ c_last
2021-02-15 00:00:00  0.95 0.96 0.91 0.92
2021-02-22 00:00:00  0.95 0.96 0.91 0.92

2021-03-08 00:00:00  0.95 0.96 0.91 0.92
2021-03-15 00:00:00  0.95 0.96 0.91 0.92
```
 '2021-02-21' is Sunday, then the expected result of Week calculate is 2021-02-15(Monday);  
 '2021-02-22/2021-02-23' are Monday/Tuesday, then the expected result of Week calculate is 2021-02-22(Monday). 

The Month calculation is easier, the start of a month is always the first day of this month, so the expected results of Month are:
```
 u       ┆ c_first ┆ c_max ┆ c_min ┆ c_last
2021-02-01 00:00:00  0.95 0.96 0.91 0.92
2021-03-01 00:00:00  0.95 0.96 0.91 0.92
```

There is [Pandas of Week definition](https://pandas.pydata.org/docs/reference/api/pandas.tseries.offsets.Week.html), hope some help for you.

**Comment by ritchie46** [comment]
Yes, I put some extra effort in now. I used `chrono`'s definitions of weeks (so I don't have to determine that.).

The week bins now start on monday and the month bins now start at the first day of the month. I hope this helps your case.

**Comment by CHCP** [comment]
I test the new Week/Month methods, that is OK.

Thank you very much @ritchie46
