### ISSUE TITLE
Series objects have no shape

### ISSUE THREAD

**Issue by dsaxton** [ritchie46/polars#486]
`Series` currently has no shape attribute (which should be a tuple containing only the length as first element):
```python
[ins] In [1]: import polars as pl

[ins] In [2]: s = pl.Series([1, 2, 3])

[ins] In [3]: s.shape
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1f0fd037afc4> in <module>
----> 1 s.shape

AttributeError: 'Series' object has no attribute 'shape'

[ins] In [4]: pl.__version__
Out[4]: '0.7.2'
```

```python
[ins] In [5]: import pandas as pd

[ins] In [6]: s = pd.Series([1, 2, 3])

[ins] In [7]: s.shape
Out[7]: (3,)

```

**Comment by ritchie46** [comment]
That's correct. They do have a [length](https://github.com/ritchie46/polars/blob/4a5990e57590dae3667ef8f98ac44c9db8e84137/py-polars/polars/series.py#L926)

**Comment by dsaxton** [comment]
> That's correct. They do have a [length](https://github.com/ritchie46/polars/blob/4a5990e57590dae3667ef8f98ac44c9db8e84137/py-polars/polars/series.py#L926)

Do you think this might be worth adding for consistency with the pandas API? I could give it a shot if you could point me to the relevant code sections (although I know very little Rust at the moment).

**Comment by ritchie46** [comment]
I don't want to be too rigid with following pandas, but in this case, it's in easy addition indeed. 

I see you already fixed it. :smile_cat:  In case you want to do a future PR with something more complex and you want to test your code you can run these steps:

* install rust nightly via[ rustup](https://www.rust-lang.org/tools/install)
* run `$ rustup override set nightly`
* `$ pip3 install maturin`
* from `root/py-polars` run `$ ./tasks.sh build-run-test`

I should add this to the contribution guide.

**Comment by dsaxton** [comment]
> I should add this to the contribution guide.

Yes, I think Rust-specific setup instructions for new contributors could be very helpful, especially since a lot may be coming from more of a Python background.
