### ISSUE TITLE
Null handling in DataFrame aggregations depends on axis

### ISSUE THREAD

**Issue by dsaxton** [ritchie46/polars#501]
```python
In [1]: import polars as pl

In [2]: df = pl.DataFrame({"a": [1, 2, 3], "b": [1, None, None], "c": [1, None, 3]})

...

In [6]: df
Out[6]:
shape: (3, 3)
╭─────┬──────┬──────╮
│ a   ┆ b    ┆ c    │
│ --- ┆ ---  ┆ ---  │
│ i64 ┆ i64  ┆ i64  │
╞═════╪══════╪══════╡
│ 1   ┆ 1    ┆ 1    │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 2   ┆ null ┆ null │
├╌╌╌╌╌┼╌╌╌╌╌╌┼╌╌╌╌╌╌┤
│ 3   ┆ null ┆ 3    │
╰─────┴──────┴──────╯

In [7]: df.mean(axis=0)
Out[7]:
shape: (1, 3)
╭─────┬─────┬─────╮
│ a   ┆ b   ┆ c   │
│ --- ┆ --- ┆ --- │
│ f64 ┆ f64 ┆ f64 │
╞═════╪═════╪═════╡
│ 2   ┆ 1   ┆ 2   │
╰─────┴─────┴─────╯

In [8]: df.mean(axis=1)
Out[8]:
shape: (3, 1)
╭──────╮
│ a    │
│ ---  │
│ f64  │
╞══════╡
│ 1    │
├╌╌╌╌╌╌┤
│ null │
├╌╌╌╌╌╌┤
│ null │
╰──────╯
```
This is because the column-wise operation uses a predefined aggregation on the underlying `_df` which seems to handle nulls natively, whereas the row-wise uses `fold` without checking for nulls.

Out of curiosity, how difficult would it be to define a transpose operation on the underlying Rust data structure @ritchie46? If that were available we'd basically have all these operations for free once they're defined column-wise.

**Comment by ritchie46** [comment]
Ah, yes. Good catch. I will need to do a second aggregation to get the null count.

> Out of curiosity, how difficult would it be to define a transpose operation on the underlying Rust data structure @ritchie46? If that were available we'd basically have all these operations for free once they're defined column-wise.

It would be quite a complex operation, and from a performance standpoint be very wasteful. As you easily have more than `n` millition rows with typically a small number of columns. That would mean we would create a large number of Series and every Series has a small overhead. Next, we need to sum millions of Series that are scattered across memory which would be very cache inefficient.

I believe that in pandas you have a block manager backed by a numpy ndarray. I think a transpose in that case is just a change of strides.

**Comment by dsaxton** [comment]
> It would be quite a complex operation, and from a performance standpoint be very wasteful. As you easily have more than `n` millition rows with typically a small number of columns. That would mean we would create a large number of Series and every Series has a small overhead. Next, we need to sum millions of Series that are scattered across memory which would be very cache inefficient.

That makes a lot of sense, thanks for the explanation
