### ISSUE TITLE
CSV failure due to invalid type inference

### ISSUE THREAD

**Issue by dsaxton** [ritchie46/polars#509]
There may be a more minimal example, but I'm not sure if this error is due to `scan_csv` or `LazyFrame.collect`:
```python
import polars as pl

pl.__version__
# '0.7.3'

file_name = "sample-data.csv"
data = '"x","y"\n"abc","100"\n'

with open(file_name, "w") as file:
    file.write(data)
    
df = pl.scan_csv(file_name)
df.collect()
```
raises
```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-6ca72d51ae28> in <module>
----> 1 df.collect()

~/venvs/polars-env/lib/python3.7/site-packages/polars/lazy/__init__.py in collect(self, type_coercion, predicate_pushdown, projection_pushdown, simplify_expression, string_cache)
    212             type_coercion, predicate_pushdown, projection_pushdown, simplify_expression
    213         )
--> 214         return wrap_df(ldf.collect())
    215 
    216     def fetch(

RuntimeError: Any(Other("Other(\"Could not parse primitive type during csv parsing: Error { code: InvalidDigit, index: 0 }\") on thread line 1; on input: \"100\""))
```
If the quotes around 100 within `data` are removed then it works.

**Comment by ritchie46** [comment]
Thanks for the bug report. This has nothing to do with laziness. This is the csv parser. The snippet below produces the same error.

```python
file_name = "sample-data.csv"
data = '"x","y"\n"abc","100"\n'

with open(file_name, "w") as file:
    file.write(data)

pl.read_csv(file_name, use_pyarrow=False)
```

What happens is that during type inference, the second column is incorrectly inferred as numerical and when a quote is found, the parser fails. 

This snippet works:

```python
file_name = "sample-data.csv"
data = '"x","y"\n"abc","100"\n'

with open(file_name, "w") as file:
    file.write(data)
    
pl.read_csv(file_name, use_pyarrow=False, dtype={"x": str, "y": str})
```

**Comment by dsaxton** [comment]
> Thanks for the bug report. This has nothing to do with laziness. This is the csv parser. The snippet below produces the same error.

Ah, I was missing `use_pyarrow=False` which was why it wouldn't reproduce for `read_csv`.

> Did you have a column where all numbers where encapsulated with quotes?

This was from a taxi cab dataset where in fact every single value was quoted. I think the inference that the field was numeric could be considered correct (IMO we'd want to make sure that simply wrapping values in quotes won't automatically change the data type to string given how common this is as a way of formatting CSV data), but that the subsequent parsing might need to handle this case. What do you think?

**Comment by ritchie46** [comment]
> I think the inference that the field was numeric could be considered correct (IMO we'd want to make sure that simply wrapping values in quotes won't automatically change the data type to string given how common this is as a way of formatting CSV data), but that the subsequent parsing might need to handle this case. What do you think?

Ah, yes I read in [RFC 4180](https://tools.ietf.org/html/rfc4180#page-2), that a field may or may not be enclosed by double quotes. I'll adapt the parser.
