### ISSUE TITLE
Creation of new columns in lazy and eager frames

### ISSUE THREAD

**Issue by stephenkraemer** [ritchie46/polars#541]
Hi,

I found this gem and am quite enthusiastic about the design and - of course - the performance :)

Since there is quite a lot to take in here, I may have overlooked it:

In a method chain for the eager API and/or within a lazy operations chain: is there a way to add new columns to a dataframe, which are not derived from existing columns? I am thinking of something similarly general as pd.DataFrame.assign or dplyr::mutate. Here is some code to illustrate my question for the lazy API:

``` python
df = pl.DataFrame(
    {
        "a": pl.Series(list('abcde')),
        "b": pl.Series(list('abcde')),
        "values_1": np.arange(5),
    }
)

res = (
    df.lazy()
    .with_columns(
        [
            # I can create a new column from existing columns
            (col("a") + col("b")).alias("a_b"),
            # I can create simple new columns from literals
            lit(1).alias('constant_int'),
            lit('abc').alias('constant_str'),
            # but how would I create for example a np.arange-based uid for each row?
            # any workaround would also help, I tried increasingly ridiculous stuff like:
            col("values_1")
            .apply(lambda ser: pl.Series(np.arange(df.height)), dtype_out=pl.Int64)
            .alias("uid"),
            # but this just gives a null column
        ]
    )
    .collect()
)
```

For the eager API, I didn't find a starting point for an .assign like functionality yet. 

If .assign-like operations are not yet possible but feasible, I would be grateful if you add them to your feature list for future consideration :)

**Comment by ritchie46** [comment]
> I found this gem and am quite enthusiastic about the design and - of course - the performance :)

Cool, let me know how it goes!

## Add eager col  in lazy
You were almost there with the increasingly ridicilous stuff. :wink: 

You can do:

```python
    df.lazy()
    .with_columns(
        [
            litl(0)
           # note the map
            .map(lambda ser: pl.Series(np.arange(df.height)), dtype_out=pl.Int64)
            .alias("uid")
        ]
    )
    .collect()
```

A `map` takes a `Series` and must produce as `Series`. An `apply` loops over the `Series` and must produce a primitive.

But, I agree that you'd want to be able to add an eager `Series` here. I will add that functionality.

## Add eager col  in eager
In eager it's more easy. :)

```python
df["uid"] = pl.Series(np.arange(df.height))
```

**Comment by stephenkraemer** [comment]
A super helpful answer, and a commit for lit(Series) in < 1h! Thank you so much!

I saw the test in the 1d9f012 - to sum up for other people perhaps looking at this issue, lazy creation of a new column from a Series is now possible with a Series literal:

``` python
    df = DataFrame({"a": [1, 2, 3], "b": [1.0, 2.0, 3.0]})
    out = df.lazy().with_column(pl.lit(pl.Series("c", [1, 2, 3]))).collect()
```

**Comment by stephenkraemer** [comment]
While I am still at the beginning here, I think the solution(s) for the lazy case cover me quite nicely!

For completeness - with the eager API:

in pandas, I find myself often using long method chains, something like (not a very convincing example, but just to give any example):

```python
(df
# sum stuff
.groupby('colA')
.mean()
.assign(sum_of_two_means=lambda df: df['colB'] + df['col'])
.sort_values(sum_of_two_means)
# more stuff
)
```

Ie I use one or more assigns within a method chain. This is compared to:

```python
temp_res = (df
.groupby('colA')
.mean()
)
temp_res['sum_of_two_means'] = temp_res['colB'] + temp_res['colA']
res = temp_res.sort_values()
```

This way, even though any eager API is of course less performant in various ways, at least I don't have another object in memory (temp_res) and I don't need to name things I am not interested in anyway.

It is not essential, but often nice for my use cases, that multiple assignments can reference previous lines, a la

```python
df.assign(colB = lambda df: df['colA'] + 1, colC = lambda df: df['colB'])
```

Just to mention a pandas usage pattern that other people might also enjoy in polars, but I am not sure if the cost/benefit for something like this in terms of implementation is reasonable.

In any case, thanks again, I am looking forward to following this projects development :)

**Comment by ritchie46** [comment]
Yes, for this reason I like the lazy API more. And with the lazy DSL you can do more without [needing python lambas](https://ritchie46.github.io/polars-book/groupby/dsl.html), which allows me to run much more in parallel.

Anyhow, the eager API should also be ergonomic, so if you have any suggestions, feel free to open a PR that allows more method chaining.

Method chaining can practically be free in Polars. All the Series data is reference counted, which means that a clone is super cheap.

**Comment by stephenkraemer** [comment]
I will try to dig deeper into the DSL then! Once I can start using this for the more experimental part of my work, I'd be happy to contribute when I come across something interesting :) But as you said, there are probably more  interesting things on the todo list at the moment than GIL-bound lambda-based assignments, so I'll try to come up with a more interesting contribution. Thanks again!

**Comment by ritchie46** [comment]
No problem! :)

I close this for now.
