### ISSUE TITLE
Compiling without nightly

### ISSUE THREAD

**Issue by elferherrera** [ritchie46/polars#550]
I am trying to integrate polar to nushell to have a Dataframe structure in the shell. One of the things that would be nice is to be able to compile polars without nightly. Based on the Readme it says that SIMD is the only thing that requires nightly, but I try to compile with `default` features and I get an error. Is there a way to compile without SIMD?

**Comment by ritchie46** [comment]
Ah, cool. I'd be interested in what that becomes.

>  I try to compile with default features and I get an error. Is there a way to compile without SIMD?

Are you using the latest master? The released version on `crates.io` is heavily outdated. But I can only update that when Arrow release a new version.

**Comment by elferherrera** [comment]
> Ah, cool. I'd be interested in what that becomes.

Yeap, it will be very useful to have an interactive tool to work with polars.

I am running from the latest from master. I managed to run the example in `various` but I had to run it in a docker container. When I run the tests I get a bunch of warnings about unused imports and this arrow error:

`method not found in chunked_array::ChunkedArray<arrow::datatypes::Time64NanosecondType>`

Initially I was running it In a mac and I was getting this error:

`error: failed to run custom build command for libmimalloc-sys v0.1.21`

It doesn't let me compile the example in `various`.

But I see now that I can compile without SIMD outside this mac.

**Comment by ritchie46** [comment]
Lately I added quite some feature gates to reduce compile times, but did not cleanup all the code snippets. After #552 is merged it should run.

P.S. I also removed the allocator, so it should compile on mac also.

**Comment by elferherrera** [comment]
Amazing. I just run the example again in a mac and it is running ok. Probably this weekend Im going to start playing with it and how to merge it into `nushell`.

Btw, what are your thoughts on `Arrow2`?

**Comment by ritchie46** [comment]
> Btw, what are your thoughts on Arrow2?

Its a very interesting development. Polars also ran into issue regarding physical types and logical types. By keeping them separate, I think we can support more datatypes whilst keeping the compilation times acceptable. Furthermore, making better use of the type system is double sliced sword. More safe and more performant. <3
