### ISSUE TITLE
use of undeclared type `CsvReader`

### ISSUE THREAD

**Issue by lucascr91** [ritchie46/polars#551]
I'm using Rust, polars version="0.12.0" in Linux (Ubuntu 20.04 LTS).

I cannot replicate documentation's [example](https://docs.rs/polars/0.12.1/polars/) as CSVReader is not being imported

Here is my code:
```
use polars::prelude::*;
use std::fs::File;

fn main() {
    let df = example();
    println!("{:?}", df)
}

fn example() -> Result<DataFrame> {
    let file = File::open("iris.csv")
                    .expect("could not read file");

    CsvReader::new(file)
            .infer_schema(None)
            .has_header(true)
            .finish()
}
```
which returns the error:

```rust
error[E0433]: failed to resolve: use of undeclared type `CsvReader`
  --> src/main.rs:13:5
   |
13 |     CsvReader::new(file)
   |     ^^^^^^^^^ use of undeclared type `CsvReader`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0433`.
```

It looks like CSVReader is not being imported by `use polars::prelude::*; ` statement. I also tried to import this struct using variations like `use polars::frame::csv::CsvReader;`

How can I import CsvReader?

**Comment by ritchie46** [comment]
Can you try adding the `csv-file` feature?

**Comment by lucascr91** [comment]
I added the mentioned feature to Cargo.toml:
```
[dependencies]
polars = {version="0.12.0", git = "https://github.com/ritchie46/polars", features = ["csv-file"] }
```

Now it works! Thanks!

**Comment by ritchie46** [comment]
Great! :smile:
