### ISSUE TITLE
Version Support for Python 3.7 & 3.8

### ISSUE THREAD

**Issue by Tian-Le97** [ritchie46/polars#558]
I noticed that Polars has been supporting Python 3.7 - 3.9 up till the version 0.7.0_beta.1, and after which, the support for higher versions of Python has been dropped entirely, only supporting Python 3.6.

I was wondering if there were any plans to bring back the support for higher versions of Python, specifically 3.7, as that is the version I am using most extensively for my personal and work uses currently.

Thank you!

[PS: Thank you for fixing the date conversion issues from Pandas to Polars highlighted previously!]

**Comment by ritchie46** [comment]
Hi, the wheel are compiled with the stable [abi3](https://pyo3.rs/v0.13.2/building_and_distribution.html#py_limited_apiabi3). In our case this means it should every python version above 3.6.

Did you have any issues installing with `$ pip install polars`? If so, which OS are you on?

**Comment by Tian-Le97** [comment]
Hi, apologies for the trouble! Seems like upgrading pip to the latest version has resolved the issue of being unable to install the package. It was previously unable to install any versions that "does not support Python 3.7", and hence, the installation using `$ pip install polars` only allows my machine to install till version 0.7.0_beta.1.

Sorry for the trouble, and thank you for helping!

**Comment by ritchie46** [comment]
No problem! :)
