### ISSUE TITLE
Does Polars support datetime as timestamp?: Csv parse timestamps as Date64

### ISSUE THREAD

**Issue by CHCP** [ritchie46/polars#560]
Hi @ritchie46 
  We discussed a lot of OHLC calculate before. #381 

  Does Polars support datetime as timestamp like this:

```
AUDCAD,1616455919,0.91212,0.95556,1
AUDCAD,1616455920,0.92212,0.95556,1
AUDCAD,1616455921,0.96212,0.95666,1
```
I define the Schema like this:
```
    Schema::new(vec![
        Field::new("s", DataType::Utf8),
        //Field::new("u", DataType::Utf8),
        //Field::new("u", DataType::Time64(TimeUnit::Millisecond)),
        Field::new("u", DataType::Date64),
        Field::new("c", DataType::Float32),
        Field::new("a", DataType::Float32),
        Field::new("v", DataType::Int64),
    ])
```

But there are some run error.
```
Unsupported data type Date64 when reading a csv
```

Thank you very much.

**Comment by ritchie46** [comment]
At the moment, you'll have to parse as`Int64` and then cast to `Date64`, but leave this issue open, I will make sure that this will be done implicitly for you.

**Comment by CHCP** [comment]
Thanks ritchie46， I will try this.

**Comment by clouds56** [comment]
what about Float64 with milliseconds, I have value `1514165998.465` and it would be interpreted as
```
+-------------------------+
| Timestamp               |
| ---                     |
| date64(ms)              |
+=========================+
| 1970-01-18 12:36:05.998 |
+-------------------------+
```

**Comment by ritchie46** [comment]
Your floating point value seems to be in seconds. You first have to parse as float, multiply `* 1000` and then coerce to `Date64`

**Comment by clouds56** [comment]
Thanks, I'm trying to achieve this by
```rust
df.apply("Timestamp", |timestamp| timestamp.f64().unwrap().apply_cast_numeric::<_, polars::datatypes::Date64Type>(|t| t as i64 * 1000))?;
```

How would you implement it if you would like to do the same?

**Comment by ritchie46** [comment]
```rust
df.may_apply("Timestamp", |s| (s * 1000).cast::<Date64Type>())
```
