### ISSUE TITLE
[Python] Column Name is lost up on conversion from decimal to float

### ISSUE THREAD

**Issue by potter420** [ritchie46/polars#562]
#### Are you using Python or Rust?

 **Python**

#### What version of polars are you using?

0.7.7

#### What operating system are you using polars on?

Amazon Linux 2

#### Describe your bug.

Column Name is lost up on conversion from decimal to float

#### What are the steps to reproduce the behavior?

```
import polars as pl
import pyarrow as pa
df_test = pa.table({
    'a': pa.array([1,2,3,4,5], pa.decimal128(38,2)),
    'b': pa.array([1,2,3,4,5], pa.int64())
})
print(df_test)
pl.from_arrow(df_test)
```

#### What is the actual behavior?
```
pyarrow.Table
a: decimal(38, 2)
b: int64
column_0 | b
-- | --
f64 | i64
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
```

#### What is the expected behavior?

The column name should be `a` in the above example

**Comment by ritchie46** [comment]
Thanks for your issue report!
