### ISSUE TITLE
Extend window functions with split-apply-combine pattern

### ISSUE THREAD

**Issue by rlmwang** [ritchie46/polars#566]
### Firstly

I really appreciate your project. Pandas played an essential role in making Python the go-to language for data science. But it has many gotchas, creating a barrier of entry for new data scientists that could be lowered. For me, Polars has the potential to be a strong addition-alternative to Pandas, creating a healthy environment for the growth of both projects.

### Request

Add `col('column').apply(UDF).over('groups')` functionality for split-apply-combine use cases.

### Example

Start the same way as in [split-apply-combine](https://ritchie46.github.io/polars-book/how_can_i/split_apply_combine.html):

```python
def mkdiff(cumcases: pl.Series) -> pl.Series:
    """
    Creates a new Series with differences per row
    """
    return cumcases - cumcases.shift(1)

base_df = (
    df.lazy()
    .with_column(col("date").str_parse_date(pl.Date32))
    .with_column(
        (col("uid").cast(str) + lit("-") + col("date").cast(int)).alias("sort_key")
    )
    .sort("sort_key")
)
```

But then finish the pattern similar to [window functions](https://ritchie46.github.io/polars-book/how_can_i/apply_window_functions.html):

```python
out = base_df.with_columns(
    [
        col("cumcases").apply(mkdiff).over("uid").alias("diff_cases"),
    ]
)
```
This should work for any UDF that returns a Series of the same length (or returns a single value like with window functions).

### Motivation

A common use case of split-apply-combine is exemplified in the [User Guide](https://ritchie46.github.io/polars-book/how_can_i/split_apply_combine.html): apply a function to each group that returns a series of the same length as the group.

The solution in the User Guide is the typical one: groupby --> apply --> explode --> join. 

This pattern has a difficult mental model, because it forces the user to understand that apply produces a list of Series (or Series of Series?) and that those should be flattened and rejoined to the Dataframe. Also, you have to remember to do a similar operation to all within-group keys, so that the result can be rejoined. For new data scientists it can be challenging to recognize this pattern in similar problems. 

I am not familiar with the internals of Polars, but my guess is that the groupby-apply-explode-join pattern is hard to optimize for performance.

Dataframes often encourage a functional programming style: compositions of functions with the signature Callable[Dataframe | Series, Dataframe | Series]. The groupby-apply-explode-join is monad-like (flatmap is just a map-flatten pattern). Monad-like patterns tend to be difficult, so I think it is a good idea to turn them into features. Of course without being precise what a monad is, or calling it one.

Use cases are: 

- Order aware window functions: lags, diffs, rolling aggregates.

- Aggregates on stacked tables: suppose you have a dataframe with columns `['uid', 'category', 'score']`, where each uid has a score per category from a classifier model. We still have to apply the final softmax layer to get probabilities. This is data from a relational database. 
It would be great if there is an easy way to compute the softmax for each category over each uid. In this case you could first compute the divisor with a window function. But this means that the user should be willing to first split an existing UDF into agregate and non-aggregate parts, reducing code readability and reusability.

**Comment by ritchie46** [comment]
Hi, I believe that the feature you request already exists. :)

However in this case, it produces a different result than the `explode`, `join` combination.

The explode turns this list `[1, 2, 3]` in this `Series`

```
[
   1,
   2,
   3
]
 ```
 
 The numbers, (not the lists) will be joined back on the groups. With a window function, the lists will be joined on the groups.
 
 The correct result of the explode-join snippet, (after [this PR](https://github.com/ritchie46/polars/pull/567/checks?check_run_id=2410178237) is merged) is this:

```python
out = (
    base_df.groupby("uid")
    .agg(
        [
            col("date").list().alias("date"),
            col("cumcases").apply(mkdiff).alias("diff_cases"),
        ]
    )
    .explode(["date", "diff_cases"])
    .join(base_df, on=["uid", "date"])
)
```
 
 ```
 shape: (5, 5)
╭─────┬──────────────┬────────────┬──────────┬───────────╮
│ uid ┆ date         ┆ diff_cases ┆ cumcases ┆ sort_key  │
│ --- ┆ ---          ┆ ---        ┆ ---      ┆ ---       │
│ i64 ┆ date32(days) ┆ i64        ┆ i64      ┆ str       │
╞═════╪══════════════╪════════════╪══════════╪═══════════╡
│ 0   ┆ 2020-12-20   ┆ null       ┆ 20       ┆ "0-18616" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-21   ┆ 20         ┆ 40       ┆ "0-18617" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-22   ┆ 27         ┆ 67       ┆ "0-18618" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-23   ┆ 13         ┆ 80       ┆ "0-18619" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 2020-12-20   ┆ null       ┆ 40       ┆ "1-18616" │
╰─────┴──────────────┴────────────┴──────────┴───────────╯
 ```
 
 Where the window functions produce this:
 
 ```python
 out = base_df.with_columns(
    [
        col("cumcases").apply(mkdiff).over("uid").alias("diff_cases"),
    ]
)
 ```
 
 ```
 ╭─────┬──────────────┬──────────┬───────────┬──────────────────────╮
│ uid ┆ date         ┆ cumcases ┆ sort_key  ┆ diff_cases           │
│ --- ┆ ---          ┆ ---      ┆ ---       ┆ ---                  │
│ i64 ┆ date32(days) ┆ i64      ┆ str       ┆ list [i64]           │
╞═════╪══════════════╪══════════╪═══════════╪══════════════════════╡
│ 0   ┆ 2020-12-20   ┆ 20       ┆ "0-18616" ┆ "[null, 20, ... 13]" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-21   ┆ 40       ┆ "0-18617" ┆ "[null, 20, ... 13]" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-22   ┆ 67       ┆ "0-18618" ┆ "[null, 20, ... 13]" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 0   ┆ 2020-12-23   ┆ 80       ┆ "0-18619" ┆ "[null, 20, ... 13]" │
├╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ 1   ┆ 2020-12-20   ┆ 40       ┆ "1-18616" ┆ "[null, 40, ... 26]" │
╰─────┴──────────────┴──────────┴───────────┴──────────────────────╯
 ```
 
 Notice the difference in the `diff_cases` column?

**Comment by ritchie46** [comment]
@rlmwang In the [new beta release](https://pypi.org/project/polars/0.7.10_beta.1/) you can do the example above entirely in window functions. Check:

https://ritchie46.github.io/polars-book/how_can_i/det_group_statistics.html#window-functions-

I will close this, as I think this is solved.

**Comment by rlmwang** [comment]
Thanks for the reply. I was writing up a response, but this link to the beta version already looks much better. 

Split-apply-combine covers many common use cases, and I am glad to see a dataframes project that makes it accessible.
