### ISSUE TITLE
Polars ML

### ISSUE THREAD

**Issue by abaspinar** [ritchie46/polars#580]
#### Supporting Machine Learning Functionality

Hi,

I've been following the project for a while and I was wondering if it is planned to support some machine learning algorithms directly with Polars in the future. 

What I think is something like Vaex-ml to support some preprocessing, Scikit-learn models and preferable some GBT like XgBoost.

Thanks a lot.

**Comment by ritchie46** [comment]
Hi @abaspinar, this is not really the scope of the project. I believe a tool should do one thing very well and be able to interact with other tools. In case of ML, Polars can expose data as numpy arrays (can be zero copy), pandas DataFrames, arrow arrays (zero copy), native Python lists, so I believe this makes interacting with `scikit-learn`, `XgBoost`, `pytorch` etc. as fast as it gets.

**Comment by abaspinar** [comment]
Thanks a lot for the answer.
