### ISSUE TITLE
Pandas - Polars: the same parquet file - different result

### ISSUE THREAD

**Issue by Vasilyeu** [ritchie46/polars#581]
#### Are you using Python or Rust?

**Python**.

#### What version of polars are you using?

0.7.9

#### What operating system are you using polars on?

Linux Ubuntu

#### Describe your bug.

Reading the same file using pandas and polars gives different result:
1. In polars float column rounded ('frequency' column)
2. Categorical column ('db') in polars shown as int32. How can I convert it to string values (like in pandas)?

#### What are the steps to reproduce the behavior?

See screenshot

#### What is the expected behavior?

I expect dataframe like in pandas

<img width="846" alt="Screenshot 2021-04-26 at 17 12 24" src="https://user-images.githubusercontent.com/16106161/116099112-4eb8f380-a6b4-11eb-9e5e-b5cdacd42e45.png">

Then I merge the dataset with another dataset and got different results for pandas and polars
<img width="843" alt="Screenshot 2021-04-26 at 17 47 16" src="https://user-images.githubusercontent.com/16106161/116102724-9bea9480-a6b7-11eb-8a41-5a952c2c65a9.png">

All values in joined columns of polars dataframe are null
<img width="387" alt="Screenshot 2021-04-26 at 17 50 46" src="https://user-images.githubusercontent.com/16106161/116103373-30ed8d80-a6b8-11eb-8d29-fff83bce6368.png">

**Comment by ritchie46** [comment]
Can we break this down a bit? I assume you are joining a categorical column with a string/ categorical column from another data source?

For this to work. You need to set a global string cache. 

But first let's look at the problem at hand. Could you perhaps send met the first 10 rows of the parquet file?

For the time being, you can load the parquet file with pyarrow and then use `pl.from_arrow` to read the table. If the `categorical` are still numeric values, you first need to cast them to strings in pyarrow. Let me know how it goes!.

**Comment by Vasilyeu** [comment]
Read parquet file with pandas, convert Categorical column to string and then convert to polars dataframe with function polars.from_pandas() solve all problems.

**Comment by ritchie46** [comment]
> Read parquet file with pandas, convert Categorical column to string and then convert to polars dataframe with function polars.from_pandas() solve all problems.

Great, that's exactly what
