### ISSUE TITLE
Reduce the occupied memory  in new TAG py-polars-0.7.9

### ISSUE THREAD

**Issue by CHCP** [ritchie46/polars#582]
#### Are you using Python or Rust?
**Rust**

#### Which feature gates did you use?
"temporal", "simd", "dtype-date64", "pretty_fmt", "downsample", "csv-file" 

#### What version of polars are you using?

py-polars-v0.7.9

#### What operating system are you using polars on?

Ubuntu 18

#### Describe your bug.

Hi @ritchie46 
  When I use version py-polars-0.7.6,  the memory is 33M while the binary execute file is running,  but when I upgrade to py-polars-0.7.9, the memory increase to 93M.   Is there any way to reduce the occupied memory?  Thanks.
 The difference features between 0.7.6 and 0.7.9 is:
```
polars = {git = "https://github.com/ritchie46/polars", tag = "py-polars-v0.7.6", default_features = false, features = ["temporal", "simd", "dtype-date64", "pretty_fmt", "downsample"]} 

polars = {git = "https://github.com/ritchie46/polars", tag = "py-polars-v0.7.9", default_features = false, features = ["temporal", "simd", "dtype-date64", "pretty_fmt", "downsample", "csv-file"]} 
```

![image](https://user-images.githubusercontent.com/5645296/116168409-a3f11580-a745-11eb-9f64-b8a1b710c1e8.png)

**Comment by ritchie46** [comment]
I think this may be because I removed the mimalloc memory allocator.  Could you set mimalloc as global allocator and see what happens? https://docs.rs/mimalloc/0.1.25/mimalloc/

**Comment by CHCP** [comment]
Hi @ritchie46 
  I change code like this:

Cargo.toml
```
[dependencies]
mimalloc = "0.1.25"
```

src/main.rs
```
use mimalloc::MiMalloc;
#[global_allocator]
static GLOBAL: MiMalloc = MiMalloc;
```

the occupied memory is 400M, 
it is too much.

![image](https://user-images.githubusercontent.com/5645296/116208198-ff41f880-a783-11eb-9747-1dbfea9c17d8.png)


Then I changed the Cargo.toml file:
```
[dependencies]
mimalloc = { version = "*", default-features = false }
```

the occupied memory is 295M, 
it is too much also.

![image](https://user-images.githubusercontent.com/5645296/116208518-5942be00-a784-11eb-81e4-26bf923ae9da.png)

I don't know the usage is correct or not?

**Comment by ritchie46** [comment]
I'd need a bit more information. Memory allocators often don't return free'd memory to the OS, so the peak memory usage remains the claimed memory. If this is problematic (and it often is not, because that free occupied memory will be reused), you need to prevent memory peaks.

I think they mostly occur while csv-parsing + rechunking. You can choose to not rechunk after csv parsing. This will cost a bit performance.

**Comment by CHCP** [comment]
What information do I need provide?

How to non-rechunk after csv parsing?

**Comment by ritchie46** [comment]
I would need to see what you do (e.g. see your code) to get an idea where the memory usage come from. Perhaps you can profile your memory usage after different operations?

> How to non-rechunk after csv parsing?

https://ritchie46.github.io/polars/polars_io/csv/struct.CsvReader.html#method.with_rechunk

**Comment by CHCP** [comment]
Sure, some code as follows, hope to help you.

There are more than 200 csv files, each file will be processed to generate 10 periods OHLC values:

```
pub fn process_csv_file() {
    ...
    match df_result {
        Ok(mut df) => {
            let cast_fmt = Some("%Y%m%d %H:%M:%S%.6f");
            df.may_apply("u", |s| s.utf8().unwrap().as_date64(cast_fmt)).unwrap();            
            
            down_sample(&df, M1_DURATION, &mut value.m1);
            down_sample(&df, M5_DURATION, &mut value.m5);
            down_sample(&df, M15_DURATION, &mut value.m15);
            down_sample(&df, M30_DURATION, &mut value.m30);
            down_sample(&df, H1_DURATION, &mut value.h1);
            down_sample(&df, H2_DURATION, &mut value.h2);
            down_sample(&df, H4_DURATION, &mut value.h4);
            down_sample(&df, D1_DURATION, &mut value.d1);
            calculate_base_ohlc_week_month(&mut value.w1, &mut value.mn);
            debug!("Iterate BASE_OHLC_MAP, key = {:?}, value = {:?}", value.m1.s, value);
        }
   ...
```

The OHLC code is: 
```
pub fn down_sample() {
    ...
    //calculate df ohlc    
    let df_ohlc = df.downsample("u", rulec).unwrap()
        .agg(&[("c", &["first", "max", "min", "last"])]).unwrap()
        .sort("u", false).unwrap();
    debug!("Symbol = {}, period type = {}, ohlc = {:?}", value.s, value.t, df_ohlc);
    
    let height = df_ohlc.height();
    if 0 == height {
        error!("Data frame OHLC is null. ohlc = {:?}", value);
        return;
    }

    //get u
    for col in df_ohlc.select_series(&["u"]).unwrap() {
        let val = col.get(height - 1).to_string();
        value.u = stand_ohlc_datetime_to_utc(&val).timestamp();
        debug!("Symbol = {}, period type = {}, base ohlc u = {}. val = {}", value.s, value.t, value.u, val);
    }

    //get o/h/l/c
    let mut ohlc: Vec<f32> = vec![];
    for col in df_ohlc.select_series(&["c_first", "c_max", "c_min", "c_last"]).unwrap() {
        if let Some(val) = col.f32().unwrap().get(height - 1) {
            ohlc.push(val)
        }
    }
    debug!("Ohlc values = {:?}", ohlc);
    value.o = ohlc[0];
    value.h = ohlc[1];
    value.l = ohlc[2];
    value.c = ohlc[3];

   ...
```

**Comment by CHCP** [comment]
Hi @ritchie46 
  I tested the newest version ploars-0.13.1,  the occupied memory is 49M, I think it is normal.

  The code changed so fast,  I will use the stable version for a long time. Thanks for your help.

**Comment by ritchie46** [comment]
Ok, then I will close this one. :+1:
