### ISSUE TITLE
parquet io

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#61]

**Comment by nevi-me** [comment]
Hi Ritchie, we're working on arrow->parquet writer at https://github.com/apache/arrow/tree/rust-parquet-arrow-writer, and I try keep the branch close to the main branch. It should work for your dataframe purposes as the non-deeply nested lists and structs are what I'm working on now, but simpler schemas work fine so far.

If I can get/make enough time on weekends, I hope to complete the nested support in time for the next release, but will likely merge the parquet branch by the next release regardless.

**Comment by ritchie46** [comment]
Perfect. This one I really was missing for interchangeability with Pandas Python. Polars only supports` LargeLists` as nested structures (I don't know if deeply nested Lists work?), but a subset of Parquet is already of much utility.

**Comment by YuRiTan** [comment]
Some arg/kwarg to (optionally) skip reading/writing the index

**Comment by nevi-me** [comment]
> Polars only supports LargeLists as nested structures (I don't know if deeply nested Lists work?)

I have to check if we support `LargeList`, but in terms of nesting, you'll currently be able to save `{Large}List<{PrimitiveBoolean||String|Binary}>`, but nothing where you have a struct or another list inside the list.

> but a subset of Parquet is already of much utility

Yes, in the typical case where you have a flat structure, that'll work.

**Comment by ritchie46** [comment]
@nevi-me Great work on the release on arrow 2.0. I see a huge performance increase in filtering operations (probably due to the scalar comparison being SIMD and the better filtering kernel itself). You mentioned parquet writing being released in 2.0 as well. I didn't find it directly in parquets or arrows docs. Am I missing something, or will it have to wait?

**Comment by nevi-me** [comment]
No, we've pushed parquet <> arrow IO down to 3.0.0. I wasn't happy with merging the work so far.

If you want to use it in the interim (we'd love feedback and help), you can use the `rust-parquet-arrow-writer` branch, which I'll keep up to date with the main branch until we get to 3.0.0 or the work is done

**Comment by ritchie46** [comment]
Added in 6c2e697815e59e6963f0055184d963a7e5b2e919

Great work @nevi-me :+1:
