### ISSUE TITLE
[Bug] `series_equal` behavior is wrong with nullable series

### ISSUE THREAD

**Issue by zirconium-n** [ritchie46/polars#72]
``` rust
    #[test]
    fn series_equal() {
        let s = Series::new("cat", vec![Some(1i64)]);
        assert!(s.series_equal(&s));  // this passes

        let s = Series::new("cat", vec![None, Some(1i64)]);
        assert!(s.series_equal(&s));  // this fails
    }
```

**Comment by ritchie46** [comment]
This is actually expected behaviour, as comparing two `None` values yield `false`. The elementwise comparison for this will lead to a `[false, true]`, because the `None` values aren't `Eq`. Maybe i could add a `series_partial_eq` method. :thinking:

**Comment by alippai** [comment]
Even Pandas struggles with this issue see:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.compare.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.compare.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html

and the ultimate
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_series_equal.html

**Comment by ritchie46** [comment]
> Even Pandas struggles with this issue, see:
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.compare.html
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.equals.html
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.compare.html
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_frame_equal.html
> 
> and the ultimate
> https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.testing.assert_series_equal.html

Yes, there are several option you could consider for comparison. For now I've added an extra method that regards missing values as being equal. For floating point values, you also have the question what to do with `NaN` and `Inf`.
