### ISSUE TITLE
implement rayon ParallelIterator for ChunkedArrays

### ISSUE THREAD

**Issue by ritchie46** [ritchie46/polars#79]
Already implemented for `Utf8Type`. For optimal aligned primitive types we can use the slices. Booleans and not optimally aligned chunks could use an implmentation.

See: https://github.com/ritchie46/polars/blob/master/polars/src/chunked_array/par/utf8.rs

**Comment by marioloko** [comment]
What should be taken into account when implementing parallel iterators for aligned primitives and booleans?

I mean, is there any problem with this implementation that will make it inefficient for primitive times or boolean:
```rust
impl<'a> Producer for Utf8Producer<'a> {
    ...
    fn into_iter(self) -> Self::IntoIter {
        // TODO: slice and create normal iterator?
        let iter = (0..self.len).into_iter();
        Utf8Iter { ca: self.ca, iter }
    }
    ...
}

impl<'a> Iterator for Utf8Iter<'a> {
    ...
    fn next(&mut self) -> Option<Self::Item> {
        self.iter.next().map(|idx| unsafe {
            mem::transmute::<Option<&'_ str>, Option<&'a str>>(self.ca.get(idx))
        })
    }
    ...
}
```

I know that for primitive types and boolean we can directly copy them, instead of using references, but I don't know if there are other factors to take into account when implementing the solution.

**Comment by ritchie46** [comment]
The implementation that is there could be used as a blueprint for the primitives (including booleans).  With iterators I make a distinction between a has null value case and one that has not.

For "regular" iterators I use the following traits;
* `Iterator` -> This is for ChunkedArrays that have null values and thus return an `Option<T::Native>` or `Option<&str>`
* `NoNullIterator` -> This is for ChunkedArrays that have no null values and thus return `T::Native` or `&str`. These don't have to be optimally aligned. There are multiple implementations of this trait such that the fastest iterator is chosen.

**Both traits are implemented on ChunkedArrays with multiple chunks or a single chunk and the faster iterator is chosen dependent on the chunk layout.**

This principle, I also wanted to have with parallel iterators. For this reason `IntoParallelIterator` is implemented for `&'a Utf8Chunked` and for `NoNull<&'a Utf8Chunked>` the `NoNull<>` is just a wrapper to make the type system happy. 

I see that the NoNull variant is only implemented for a single chunk (*Cont* from contiguous) and also should be implemented for multiple chunks, with no null values.

Once that is done, the exact same could be done for the primitive types. 

There is a bit added complexity because I want the fastest path for the iterator depending on the chunk layout. I hope this elaboration makes it a bit more clear?

**Comment by marioloko** [comment]
Yes, I understand. I guess that is the developer the one in charge to decide which iterator layout to use, isn’t it?. I would try to do the following:
1. Implement the NoNull variant for multiple chunks for Utf8.
2. Add tests to verify that the parallel iterators are working for Utf8.
3. Implement the parallel iterator for other types.

**Comment by ritchie46** [comment]
> Yes, I understand. I guess that is the developer the one in charge to decide which iterator layout to use, isn’t it?.
Indeed. I haven't documented this yet, but internally a lot of operations have multiple implementations, One for each iterator layout.

 I would try to do the following:

    Implement the NoNull variant for multiple chunks for Utf8.
    Add tests to verify that the parallel iterators are working for Utf8.
    Implement the parallel iterator for other types.

Cool! In case I didn't mention it I appreciate your help. :)

**Comment by marioloko** [comment]
I've been checking the implementation of `iterators.rs` and it seems that there are 5 kind of `Iterator` implementation for each type.

For example, for Utf8:
```rust
pub struct Utf8IterCont<'a>; // Single Contiguous
pub struct Utf8IterSingleChunk<'a>; // Single Chunk No Null
pub struct Utf8IterSingleChunkNullCheck<'a>; // Single Chunk Nullable
pub struct Utf8IterManyChunk<'a>; // Many Chunk No Null
pub struct Utf8IterManyChunkNullCheck<'a>; // Many Chunk Nullable
```

I understand most of the iterators but I am not sure about the differences of `Utf8IterCont` and `Utf8IterSingleChunk`, as both are one chunk iterators that work with `NoNull`. The differences that I see in the code is that the former returns `Option<&'a str>` while the later returns `Option<Option<&'a str>>` (equally to the nullable version `Utf8IterSingleChunkNullCheck`, but never returning `None`).

For parallel Iterators I just see:
```rust
pub struct Utf8IntoIter<'a>; // Works with `self.ca.get(idx)` as maybe there are many chunks (Nullable)
pub struct Utf8IntoIterCont<'a>; // Works with `self.arr.value(idx + self.offset)` as the data is in a contiguos array. (Not Null)
```

So I think that at least `NoNull<>` implementation is missing for the first type and Null implementation is missing for the second, correct me if I am wrong.

**Comment by ritchie46** [comment]
Yes.. there are 5 implementations of the `Iterator` trait (and there should be even one more)

## IntoNoNullIterator
return types: `&str`
* `struct Utf8IterCont<'a>;`
    * single chunk
* *We miss a many chunks impl*

## IntoIterator
return types: `Option<&str>`
* `Utf8IterSingleChunk<'a>`  
    * single chunk; there are no nulls, so we don't check it internally but we do return an `Option`
* `Utf8IterSingleChunkNullCheck<'a>`
   * single chunk; we do null checking
* `Utf8IterManyChunk<'a>`
 Yes.. there are 5 implementations of the `Iterator` trait (and there should be even one more)

## IntoNoNullIterator
return types: `&str`
* `struct Utf8IterCont<'a>;`
    * single chunk
* *We miss a many chunks impl*

## IntoIterator
return types: `Option<&str>`
* `Utf8IterSingleChunk<'a>`  
    * single chunk; there are no nulls, so we don't check it internally but we do return an `Option`
* `Utf8IterSingleChunkNullCheck<'a>`
   * single chunk; we do null checking
* `Utf8IterManyChunk<'a>`
    * many chunks; no null checking internally, but we do return an Option
*  `Utf8IterManyChunkNullCheck<'a>`
    * many chunks; we do null checking

When I wrote the iterators. I didn't figure out how to do fast indexing yet. The arrow trait downcasts fom `dyn Array` with the `Any` trait, meaning that there is a runtime overhead of every index to check the types. Later I have been able to do this with [pointer casting](https://github.com/ritchie46/polars/blob/9f27e7326b631bb244b20f735c9dc376c0c05403/polars/src/chunked_array/ops/take.rs#L15). So I could implement fast indexing with the `TakeRandom` trait. That's why I could use that trait in the Parallel implementation.

However, I think the 6 implementations used in the `impls` for the `Iterator` trait are better, because in the case of a single chunk, we have less bound checking. I.e. we know that we are in a single chunks so we dont have to translate an index to a `chunk_idx` and an `array_idx` as we do [here](https://github.com/ritchie46/polars/blob/9f27e7326b631bb244b20f735c9dc376c0c05403/polars/src/chunked_array/mod.rs#L411).

The gist: that we have that many implmentations to find the fastest possible path with minimal bound checking per iteration. 

>>So I think that at least NoNull<> implementation is missing for the first type and Null implementation is missing for the second, correct me if I am wrong.   * many chunks; no null checking internally, but we do return an Option
*  `Utf8IterManyChunkNullCheck<'a>`
    * many chunks; we do null checking

When I wrote the iterators. I didn't figure out how to do fast indexing yet. The arrow trait downcasts fom `dyn Array` with the `Any` trait, meaning that there is a runtime overhead of every index to check the types. Later I have been able to do this with [pointer casting](https://github.com/ritchie46/polars/blob/9f27e7326b631bb244b20f735c9dc376c0c05403/polars/src/chunked_array/ops/take.rs#L15). So I could implement fast indexing with the `TakeRandom` trait. That's why I could use that trait in the Parallel implementation.

However, I think the 6 implementations used in the `impls` for the `Iterator` trait are better, because in the case of a single chunk, we have less bound checking. I.e. we know that we are in a single chunks so we dont have to translate an index to a `chunk_idx` and an `array_idx` as we do [here](https://github.com/ritchie46/polars/blob/9f27e7326b631bb244b20f735c9dc376c0c05403/polars/src/chunked_array/mod.rs#L411).

The gist: that we have that many implmentations to find the fastest possible path with minimal bound checking per iteration. 

>So I think that at least NoNull<> implementation is missing for the first type and Null implementation is missing for the second, correct me if I am wrong.

Yes, I think you are right. I think we should make the difference a bit more clear than how it is now defined. 
We have:
* No null; return type `T`
* No null; return type `Option<T>`
So maybe we should refactor the name, such that the return types are also clear.

**Comment by marioloko** [comment]
Yes, after seeing the implementation of the `get` method, I agree with you that implementing the iterators the same way as they are in [iterators.rs]() is better, as the use of `get` in the single chunk solution has more checking, and in the many chunks solution has to figure out in which chunk it is, iterating over the previous chunks again and again, as shown in the snipped below:

```rust
    pub(crate) fn index_to_chunked_index(&self, index: usize) -> (usize, usize) {
        ...
        for chunk in &self.chunks {
            let chunk_len = chunk.len();
            if chunk_len - 1 >= index_remainder {
                break;
            } else {
                index_remainder -= chunk_len;
                current_chunk_idx += 1;
            }
        }
        ...
    }
```

In contrast with the solution provided by `Iterators` that keeps in its state the chunk in which is located the current chunk.

Ok, so everything understood, I will try to start with the implementation. I'll add further documentation to explain the different types. Thanks! 😄

**Comment by marioloko** [comment]
I started implementing the solution and I think of 3 ideas:

1. Reimplement the iterators in the parallel module. It will be basically a copy paste in the parallel module of the iterator implementation for each iterator. I don't like this solution because it generates duplicated code.

2. Reuse the current implementation of iterators for the producer. That is:
```rust
impl<'a> Producer for Utf8Producer<'a> {
    ...
    fn into_iter(self) -> Self::IntoIter {
        Utf8IterSingleChunk {
            self.ca.downcast_chunks()[0],
            self.offset,
            self.len
        }
    }
   ...
}
```
I prefer the second solution to the first one, but there is a problem, the struct fields are private outside the `iterators.rs` module. Then, I have to create an extra constructor and make it visible just to the `chunked_array` module and its descendants.
```rust
impl<'a> Utf8IterSingleChunk<'a> {
   ...
    #[cfg(feature = "parallel")]
    pub(super) fn with_fields(
        current_array: &'a StringArray,
        idx_left: usize,
        idx_right: usize,
    ) -> Self {
        Utf8IterSingleChunk {
            current_array,
            idx_left,
            idx_right,
        }
    }
   ...
}
```
What I don't like of this solution is that it breaks the encapsulation of the iterators ported to parallel. (It allows to use the new constructor in every submodule of `chunked_array`.

3. Rearrange the modules in a way that `par` is a submodule of `iterator`. That way `par` would be able to access the private fields of `iterator` structs, but no other module would. I think I will go with this one.

What is your opinion? Do you agree with making `par` a submodule of `iterators`?

**Comment by ritchie46** [comment]
Yes.. I agree. I think it makes sense to make parallel iterators are submodule of iterators.

**Comment by marioloko** [comment]
Just as an update. I created a parallel iterator for SingleChunk, SingleChunkCheckNull, ManyChunk and ManyChunkCheckNull.

You can check the changes in [my local fork.](https://github.com/marioloko/polars/blob/utf8_no_null_multiple_chunk_parallel_iterator/polars/src/chunked_array/iterator/par/utf8.rs)

There is still a lot to do, but I will update the repo frequently until everything is ready for the pull request.

Thanks!

**Comment by marioloko** [comment]
1. Is there any reason why `Utf8IterCont` does not implement `ExactSizeIterator` and `DoubleEndedIterator` traits for sequential iterators?
I implemented these two traits, as the sequential iterator generated by `Producer` shall implement both, but I would like to know if they weren't implemented due to some reason.

2. Should I implement also the `Utf8IterManyCont` (or the name you think is correct for this) for sequential and parallel iterators?

**Comment by ritchie46** [comment]
>Is there any reason why Utf8IterCont does not implement ExactSizeIterator and DoubleEndedIterator traits for sequential iterators?
I implemented these two traits, as the sequential iterator generated by Producer shall implement both, but I would like to know if they weren't implemented due to some reason.

I really think I forgot due to the many different `impl`'s. So no, not any specific reason.

> Should I implement also the Utf8IterManyCont (or the name you think is correct for this) for sequential and parallel iterators? This commit shows what I implemented.

Yes that would be great. I think that we could refactor the name indeed to better clarify that the return type is `T` instead of `Option<T>`. Maybe `Utf8IterReturnValue` vs `Utf8IterReturnOption`?

**Comment by marioloko** [comment]
Yes, I agree with refactoring the names. I like the `Utf8IterReturnOption` as I think is clear, but not so much with `Utf8IterReturnValue` as `Option` is also a value, probably I would go with `Utf8IterReturnUnwrapped`, `Utf8IterReturnNoWrap` or `Utf8IterReturnStr`(this last one would depend chunked array type). What do you think?

**Comment by ritchie46** [comment]
'Utf8IterReturnUnWrapped' is a good one!

**Comment by marioloko** [comment]
I am refactoring the other iterators before implementing the parallel iterators for them. In the implementation of `ExactSizeIterator` I can observe this:
```rust
impl<'a, T> ExactSizeIterator for NumIterSingleChunkNullCheck<'a, T> where T: PolarsNumericType {}
impl<'a, T> ExactSizeIterator for NumIterSingleChunk<'a, T>
where
    T: PolarsNumericType,
    T::Native: Copy,
{
}
impl<'a, T> ExactSizeIterator for NumIterManyChunkNullCheck<'a, T> where T: PolarsNumericType {}
impl<'a, T> ExactSizeIterator for NumIterManyChunk<'a, T> where T: PolarsNumericType {}
```

It seems that only the `T` for `NumIterSingleChunk` has 2 constraints:
- `T: PolarsNumericType`
- `T::Native: Copy`

I think that the other Num iterators shall have also this constraint, as they should be able to hold the same types. Should I use that constraint also for the other types?

**Comment by ritchie46** [comment]
> It seems that only the T for NumIterSingleChunk has 2 constraints:
    T: PolarsNumericType
    T::Native: Copy
I think that the other Num iterators shall have also this constraint, as they should be able to hold the same types. Should I use that constraint also for the other types?

Yes.. I don't think it makes a difference. It should at least be `PolarsNumericType` (because these values are in a contiguous memory similar to rust's primitives) Booleans are not  because they are stored as bits and in rust they are stored as bytes.
Anyhow. Any numeric type is `Copy` so if you can make it work without the constraint it is also ok.

> The different iterator implementation for Num are reduced to four types, all of them return Option<T> and there is no equivalent for ReturnUnwrapped. Also there is an important difference here, in contrast with Utf8Chunked whose implementation of IntoNoNullIter returned a ReturnUnwrapped iterator, this one returns just the ReturnOption without NullCheck.

I don' t think I really understand. :sweat_smile: 

> I observe that Num iterators uses Box<T> for IntoNoNullIterator instead of a static dispatcher, as it is the case of the IntoIter implementation, which uses NumericChunkIterDispatch.

Yes, that's correct. Later I thought that the static dispatch is a premature optimization that doesn't really matter as for that single box alloc we traverse a whole array. So feel free to opt for Box. :)

**Comment by marioloko** [comment]
>I don' t think I really understand. 😅

Basically, if we compare Utf8Chunked types and Numeric types we have the following iterators:
1. Utf8Chunked
    - Utf8IterSingleChunkReturnUnwrapped
    - Utf8IterManyChunkReturnUnwrapped
    - Utf8IterSingleChunkReturnOption
    - Utf8IterSingleChunkNullCheckReturnOption
    - Utf8IterManyChunkReturnOption
    - Utf8IterManyChunkNullCheckReturnOption
2. Numeric
    - NumIterSingleChunkReturnOption
    - NumIterSingleChunkNullCheckReturnOption
    - NumIterManyChunkReturnOption
    - NumIterManyChunkNullCheckReturnOption
   (No equivalent for ReturnUnwrapped, previously Cont)

Also the `IntoNoNullIter` trait for Utf8Chunked, has as item an `&str`, instead of `Option<&str>`, while the item in Numeric iterators is `Option<T>`, while I would expect `T`, to be coherent with Utf8Chunked implementation.

> Yes, that's correct. Later I thought that the static dispatch is a premature optimization that doesn't really matter as for that single box alloc we traverse a whole array. So feel free to opt for Box. :)

I thought that the reason was that, so maybe we could remove the dispatcher also for Utf8Chunked. In order to:
1. Standardize the code.
2. Reduce the amount of code, which probably contributes also to decrease compilation time (which I saw in other thread that is a problem)

**Comment by ritchie46** [comment]
> I thought that the reason was that, so maybe we could remove the dispatcher also for Utf8Chunked. In order to:

Yes. That that is ok.

On the iterators. I see that currently for the `IntoNoNullIter` on null types we have this:
```rust
impl<'a, T> IntoNoNullIterator for &'a ChunkedArray<T>
where
    T: PolarsNumericType,
{
    type Item = T::Native;
    type IntoIter = Box<dyn Iterator<Item = Self::Item> + 'a>;

    fn into_no_null_iter(self) -> Self::IntoIter {
        match self.chunks.len() {
            1 => Box::new(
                self.downcast_chunks()[0]
                    .value_slice(0, self.len())
                    .iter()
                    .copied(),
            ),
            _ => Box::new(NumIterManyChunk::new(self)),
        }
    }
```

So the return type is `T::Native` which is correct. 
I do see that I have reused the struct `NumIterManyChunk`. It's `ReturnUnwrapped`. 

This struct is also used in the `ReturnOption` variant by just mapping a `Some` on it, e.g. the `IntoIterator` iml is just `NumIterManyChunk::into_no_null_iter().map(Some)`. 

# Overview
I think this is the first time I am able to make an overview of the iterators, when I implemented them I just wanted to make them work and didn't draw out all the combinations.

So I think all iterators should follow the same template.

## NoNullIterator
* `IterSingleChunkReturnUnwrapped`
* `IterManyChunkReturnUnwrapped`

## Iterator
* `IterSingleChunkReturnOption`
    - No null check so just map `Some` on `IterSingleChunkReturnUnwrapped`
* `IterSingleChunkNullCheckReturnOption`
* `IterManyChunkReturnOption`
   - No null check so map `Some` on `IterManyChunkReturnUnwrapped`
* `IterManyChunkNullCheckReturnOption`

P.S. As we can just map for the `IterManyChunkReturnOption` and `IterSingleChunkReturnOption` we don't have to make these structs and do the map at the dispatch point of the `IntoIterator` trait impl.

So that leaves us at:

## NoNullIterator
* `IterSingleChunkReturnUnwrapped`
* `IterManyChunkReturnUnwrapped`

## Iterator
* `IterSingleChunkNullCheckReturnOption`
* `IterManyChunkNullCheckReturnOption`

I believe that the template above has all combinations covered, or am I missing something?

**Comment by marioloko** [comment]
Oh, I did't realize that NullCheck was the only one returning option.

Ok, understood. Then, there will be just 4 iterator, and in this case there is no need anymore to keep return type in the name, as ReturnOption will always match NullCheck and ReturnUnwrap will match the others.

Cool, I start with this.

**Comment by ritchie46** [comment]
@marioloko This is completely implemented right?

**Comment by marioloko** [comment]
Yes, it is completely implemented.

There is a parallel iterator for each sequential iterator, and every parallel iterator except for the List iterator have tests to prove they are working as expected.

**Comment by ritchie46** [comment]
> Yes, it is completely implemented.

Great. again thanks for your effort on making the foundation of the library well organized. :+1:
